class_name Palette
extends RefCounted
## 統一カラーパレット（docs/10 §2-D）。全UI/ビューの色はこの定数を参照し、
## 散在する hex リテラルを一元化する。将来のパレット差し替えはここだけで済む。

# --- 海・空（明るい海） ---
const SKY_TOP := Color("#9bd6ee")
const SKY_HORIZON := Color("#c9ecf6")
const SEA_SHALLOW := Color("#2f9bd6")
const SEA_MID := Color("#1f6fa8")
const SEA_DEEP := Color("#0e3f63")
const FOAM := Color("#eaf6ff")

# --- 砂・木・羊皮紙（暖色） ---
const SAND := Color("#d8c089")
const SAND_DEEP := Color("#b69a5e")
const WOOD := Color("#8a5428")
const WOOD_HOVER := Color("#a66831")
const WOOD_PRESSED := Color("#60381f")
const WOOD_DARK := Color("#5e3a1c")
const PARCHMENT := Color("#f3e8cd")
const PARCHMENT_DEEP := Color("#e7d6ad")

# --- パネル ---
const SCREEN_BG_DEFAULT := Color("#091a2d")
const DARK_PANEL := Color("#13283f")
const DARK_PANEL_DEEP := Color("#0a1622")
const BLUE_PANEL := Color("#173b61")

# --- 金 ---
const GOLD := Color("#e1bd72")
const GOLD_BRIGHT := Color("#ffe7a8")
const GOLD_DEEP := Color("#b98a3e")

# --- ゲージ（意味色） ---
const GAUGE_GREEN := Color("#3cbf78")
const GAUGE_GREEN_HI := Color("#9ff0c0")
const GAUGE_AMBER := Color("#e0a02e")
const GAUGE_AMBER_HI := Color("#ffd277")
const GAUGE_RED := Color("#d94b4b")
const GAUGE_RED_HI := Color("#ff9a82")
const GAUGE_CYAN := Color("#2f7fd0")
const GAUGE_CYAN_HI := Color("#88bdf2")

# --- テキスト ---
const TEXT_DARK := Color("#203042")
const TEXT_BODY := Color("#31485d")
const TEXT_BONE := Color("#fff1c7")
const TEXT_OUTLINE_DARK := Color("#0a1622")
const TEXT_OUTLINE_LIGHT := Color("#3a2410")

const SHADOW := Color(0.0, 0.0, 0.0, 0.34)

# --- レアリティ ---
const RARITY_COMMON_TEXT := Color("#e9f7ff")
const RARITY_UNCOMMON_TEXT := Color("#9fffd0")
const RARITY_RARE_TEXT := Color("#f8c8ff")
const RARITY_BOSS_TEXT := Color("#ffcf83")
const RARITY_COMMON_BADGE := Color("#156d9b")
const RARITY_UNCOMMON_BADGE := Color("#287d34")
const RARITY_RARE_BADGE := Color("#7f3aa2")
const RARITY_BOSS_BADGE := Color("#9b3d24")
const RARITY_UNKNOWN_BADGE := Color("#6b4521")
const RARITY_COMMON_BORDER := Color("#8dd5f5")
const RARITY_UNCOMMON_BORDER := Color("#a7e7a1")
const RARITY_RARE_BORDER := Color("#e5b4ff")

# --- 調理場UI ---
const COOKING_TITLE_FALLBACK_BG := Color("#25170e")
const COOKING_WOOD_BORDER := Color("#70451f")
const COOKING_GOLD_TRIM := Color("#f0c06b")
const COOKING_RECIPE_TITLE_TEXT := Color("#251c12")
const COOKING_RECIPE_TITLE_OUTLINE := Color("#fff3cf")
const COOKING_RECIPE_STAR_LOCKED := Color("#d9bd72")
const COOKING_RECIPE_STAR_OUTLINE := Color("#4c2b0b")
const COOKING_RECIPE_FOOTER_TEXT := Color("#49351f")
const COOKING_RECIPE_FOOTER_OUTLINE := Color("#fff4cf")
const COOKING_RECIPE_CARD_SELECTED_FILL := Color("#ffedbb")
const COOKING_RECIPE_CARD_FILL := Color("#ead7ad")
const COOKING_RECIPE_CARD_LOCKED_FILL := Color("#dcc69b")
const COOKING_RECIPE_CARD_UNAVAILABLE_FILL := Color("#ddc99f")
const COOKING_RECIPE_CARD_SELECTED_BORDER := Color("#f2c86d")
const COOKING_RECIPE_CARD_BORDER := Color("#7b5027")
const COOKING_RECIPE_CARD_SELECTED_INNER := Color("#fff6d4")
const COOKING_RECIPE_CARD_INNER := Color("#c59a59")
const COOKING_RECIPE_THUMB_FILL := Color("#78502b")
const COOKING_RECIPE_THUMB_BORDER := Color("#4d2d15")
const COOKING_RECIPE_THUMB_INNER := Color("#d9a45a")
const COOKING_RECIPE_MATERIAL_FILL := Color("#f4dfab")
const COOKING_RECIPE_MATERIAL_INNER := Color("#d7a456")
const COOKING_PREP_BAR_FILL := Color("#e6d2a5")
const COOKING_PREP_BAR_BORDER := Color("#5e391a")
const COOKING_PREP_BAR_INNER := Color("#e3b15e")
const COOKING_PREP_CARD_FILL := Color("#f0dfb8")
const COOKING_PREP_CARD_BORDER := Color("#8b5b2c")
const COOKING_PREP_CARD_INNER := Color("#d7a456")
const COOKING_PREP_TITLE_TEXT := Color("#2b2117")
const COOKING_PREP_TITLE_OUTLINE := Color("#fff2ca")
const COOKING_PREP_VALUE_TEXT := Color("#1f160f")
const COOKING_PREP_VALUE_OUTLINE := Color("#fff5cf")
const COOKING_DETAIL_ROW_FILL := Color("#fff0cf")
const COOKING_DETAIL_ROW_BORDER := Color("#8b5b2c")
const COOKING_DETAIL_ROW_INNER := Color("#e6b561")
const COOKING_DETAIL_VALUE_TEXT := Color("#21170f")
const COOKING_DETAIL_VALUE_OUTLINE := Color("#fff3c8")
const COOKING_DETAIL_BADGE_FILL := Color("#f4dfab")
const COOKING_DETAIL_BADGE_BORDER := Color("#7b5027")
const COOKING_DETAIL_BADGE_INNER := Color("#d7a456")
const COOKING_DETAIL_BADGE_OUTLINE := Color("#fff2cf")

# --- 魚図鑑 / 台帳UI ---
const FISH_BOOK_BG_SCRIM := Color(0.02, 0.07, 0.10, 0.42)
const FISH_BOOK_FOUND_TEXT := Color("#fff2c6")
const FISH_BOOK_INK_OUTLINE := Color("#07131d")
const FISH_BOOK_TITLE_TEXT := Color("#fff0aa")
const FISH_BOOK_TITLE_OUTLINE := Color("#2a1608")
const FISH_BOOK_PAGE_WASH_TINT := Color(1.0, 0.965, 0.860, 0.46)
const FISH_BOOK_DETAIL_NAME := Color("#2a1a0c")
const FISH_BOOK_PORTRAIT_SHADOW_DETAIL := Color(0.18, 0.105, 0.040, 0.20)
const FISH_BOOK_PORTRAIT_SHADOW_CARD := Color(0.18, 0.105, 0.040, 0.16)
const FISH_BOOK_PORTRAIT_BG := Color("#f5e4ba", 0.84)
const FISH_BOOK_PORTRAIT_PAPER_TINT := Color(1.0, 0.965, 0.880, 1.0)
const FISH_BOOK_PORTRAIT_CARD_TINT := Color(1.0, 0.98, 0.88, 0.76)
const FISH_BOOK_RULE_INK := Color("#7e5a2b")
const FISH_BOOK_DETAIL_ROW_FRAME_TINT := Color(1.0, 1.0, 1.0, 0.40)
const FISH_BOOK_LABEL_PLATE := Color("#6b4521")
const FISH_BOOK_DETAIL_ROW_TITLE := Color("#fff4ce")
const FISH_BOOK_DETAIL_ROW_VALUE := Color("#3f2b17")
const FISH_BOOK_NO_OUTLINE := Color("#281607")
const FISH_BOOK_CARD_NAME := Color("#3a230e")
const FISH_BOOK_CARD_NAME_OUTLINE := Color("#2b1708")
const FISH_BOOK_BADGE_TEXT := Color.WHITE
const FISH_BOOK_CARD_DIVIDER := Color("#7c592a")
const FISH_BOOK_CARD_STAT_TEXT := Color("#2d1d0d")
const FISH_BOOK_UNDISCOVERED_RARITY := Color("#e8d0a0")
const FISH_BOOK_LOCKED_PORTRAIT := Color(0.04, 0.035, 0.03, 0.70)
const FISH_BOOK_EMPTY_SPOT_TEXT := Color("#6b5331")
const FISH_BOOK_SPOT_THUMB_TINT := Color(1.0, 0.965, 0.860, 0.92)
const FISH_BOOK_FISH_ICON_FALLBACK := Color("#8aa7b5")
const FISH_BOOK_PRIMARY_BUTTON_TEXT := Color("#fff8d8")
const FISH_BOOK_BUTTON_TEXT := Color("#2b1809")
const FISH_BOOK_PRIMARY_BUTTON_OUTLINE := Color("#2a1406")
const FISH_BOOK_BUTTON_OUTLINE := Color("#ffe5a6")
const FISH_BOOK_PRIMARY_BUTTON_SHADOW := Color(0.0, 0.0, 0.0, 0.35)
const FISH_BOOK_BUTTON_SHADOW := Color(1.0, 0.86, 0.48, 0.28)
const FISH_BOOK_PRIMARY_ICON_TINT := Color(1.0, 0.94, 0.72, 0.95)
const FISH_BOOK_ICON_TINT := Color(1.0, 0.96, 0.78, 0.85)
const FISH_BOOK_SCROLL_TRACK_BG := Color("#211407")
const FISH_BOOK_SCROLL_TRACK_BORDER := Color("#c28d2d")
const FISH_BOOK_SCROLL_GRABBER := Color("#d7a238")
const FISH_BOOK_SCROLL_GRABBER_BORDER := Color("#4d2b0d")
const FISH_BOOK_SCROLL_GRABBER_HOT := Color("#ffd06b")
const FISH_BOOK_SCROLL_GRABBER_HOT_BORDER := Color("#5b3210")
const FISH_BOOK_HEADER_CHIP_BG := Color(0.06, 0.035, 0.018, 0.62)
const FISH_BOOK_HEADER_CHIP_TEXT := Color("#fff4c7")
const FISH_BOOK_HEADER_CHIP_OUTLINE := Color("#06131d")
const FISH_BOOK_LABEL_SHADOW := Color(0.0, 0.0, 0.0, 0.25)

# --- 釣り場マップ / 航海図UI ---
const MAP_BG_TOP := Color("#08223a")
const MAP_BG_BOTTOM := Color("#030d18")
const MAP_CANVAS_BG := Color("#04111f")
const MAP_CANVAS_FALLBACK := Color("#0b4564")
const MAP_OVERLAY_DARK := Color("#020914")
const MAP_COMPASS_WASH := Color("#031321")
const MAP_TITLE_INK := Color("#241107")
const MAP_TITLE_GOLD := Color("#f5d98d")
const MAP_TITLE_OUTLINE := Color("#6a3d18")
const MAP_STATUS_MUTED := Color("#b8c4cf")
const MAP_RULE_GOLD := Color("#d4a85b")
const MAP_RIVET_FILL := Color("#614224")
const MAP_RIVET_EDGE := Color("#e8c176")
const MAP_TITLE_PLATE := Color("#d7b36d")
const MAP_TITLE_PLATE_BORDER := Color("#8a5728")
const MAP_HEADER_BACKDROP := Color("#041b2e")
const MAP_HEADER_STATUS_BG := Color("#052d49")
const MAP_HEADER_STATUS_BORDER := Color("#d1a458")
const MAP_DETAIL_FALLBACK := Color("#ead3a0")
const MAP_DETAIL_TEXT := Color("#2f2114")
const MAP_ACTION_BG := Color("#073a5b")
const MAP_ACTION_HOVER := Color("#0b4a70")
const MAP_SECONDARY_BG := Color("#d9bf83")
const MAP_SECONDARY_HOVER := Color("#ead49a")
const MAP_SECONDARY_BORDER := Color("#8b5a25")
const MAP_SECONDARY_PRESSED := Color("#b98749")
const MAP_DETAIL_ROW_TITLE := Color("#6e4a24")
const MAP_DETAIL_VALUE := Color("#1b1008")
const MAP_DETAIL_ROW_BG := Color("#ead8ad")
const MAP_DETAIL_ROW_BORDER := Color("#876036")
const MAP_FOOTER_BG := Color("#082842")
const MAP_FOOTER_TEXT := Color("#f3dca5")
const MAP_FOOTER_MESSAGE := Color("#f8e3ae")
const MAP_PROGRESS_TRACK := Color("#1a2020")
const MAP_BUTTON_TEXT_DARK := Color("#2c1b0f")
const MAP_BUTTON_TEXT_PRESSED := Color("#241308")
const MAP_FOOTER_PRIMARY_BG := Color("#073957")
const MAP_FOOTER_PRIMARY_HOVER := Color("#0a4a70")
const MAP_FOOTER_SECONDARY_BG := Color("#282a27")
const MAP_FOOTER_SECONDARY_HOVER := Color("#373a35")
const MAP_FOOTER_SECONDARY_BORDER := Color("#d0a65a")
const MAP_FOOTER_PRIMARY_PRESSED := Color("#052b43")
const MAP_FOOTER_SECONDARY_PRESSED := Color("#1e201e")
const MAP_FOOTER_INFO_BG := Color("#062d46")
const MAP_FOOTER_INFO_BORDER := Color("#d6aa5a")
const MAP_MEMO_PRIMARY_BG := Color("#073753")
const MAP_MEMO_SECONDARY_BG := Color("#062f49")
const MAP_MEMO_FRAME_BG := Color("#e7d4aa")
const MAP_LEDGER_LABEL_DIM := Color("#e4d1a2")
const MAP_LEDGER_STRONG_BG := Color("#0b405f")
const MAP_LEDGER_WEAK_BG := Color("#133f50")
const MAP_LEDGER_STRONG_BORDER := Color("#efca6e")
const MAP_LEDGER_WEAK_BORDER := Color("#c99d54")
const MAP_ENTRY_TITLE := Color("#1d140b")
const MAP_ENTRY_TITLE_LOCKED := Color("#5c554a")
const MAP_ENTRY_BADGE := Color("#7b4c15")
const MAP_ENTRY_BADGE_LOCKED := Color("#6b5740")
const MAP_ENTRY_BADGE_SELECTED := Color("#4f3518")
const MAP_ENTRY_BODY := Color("#23170d")
const MAP_ENTRY_BODY_LOCKED := Color("#4f4941")
const MAP_ENTRY_BODY_UNLOCKED_WASH := Color("#f5e5bc")
const MAP_ENTRY_BODY_LOCKED_WASH := Color("#5d605a")
const MAP_ENTRY_SELECTED_WASH := Color("#ffe070")
const MAP_ENTRY_LOCKED_RULE := Color("#4b514f")
const MAP_ENTRY_BOTTOM_RULE := Color("#7d5831")
const MAP_ENTRY_BG := Color("#ead5a7")
const MAP_ENTRY_BG_LOCKED := Color("#4f514d")
const MAP_ENTRY_BORDER := Color("#6d4b28")
const MAP_ENTRY_BORDER_LOCKED := Color("#4d463d")
const MAP_ENTRY_SELECTED_BG := Color("#f3cf66")
const MAP_ENTRY_SELECTED_BORDER := Color("#f4cf72")
const MAP_MARK_FILLED := Color("#d89132")
const MAP_MARK_EMPTY := Color("#82796b")
const MAP_MARK_LOCKED := Color("#6f6a61")
const MAP_BAR_BACK := Color("#5c5143")
const MAP_BAR_BACK_LOCKED := Color("#736d63")
const MAP_BAR_FILL := Color("#d39135")
const MAP_UNLOCK_OK := Color("#f2cf7d")
const MAP_UNLOCK_BOSS := Color("#ffb58d")
const MAP_UNLOCK_LOCKED := Color("#ffb0a0")
const MAP_CHART_BORDER := Color("#f0c761")
const MAP_GRID := Color("#f6d682")
const MAP_TICK := Color("#f8dea0")
const MAP_COMPASS_GOLD := Color("#f7dfa0")
const MAP_COMPASS_NORTH := Color("#ffdf74")
const MAP_COMPASS_SOUTH := Color("#99d8ee")
const MAP_CONTOUR_SHALLOW := Color("#f8deb0")
const MAP_CONTOUR_REEF := Color("#c8f2df")
const MAP_CONTOUR_OCEAN := Color("#89c8e8")
const MAP_CONTOUR_INNER := Color("#fff0b0")
const MAP_CURRENT_BLUE := Color("#bfeaff")
const MAP_CURRENT_GOLD := Color("#f7d979")
const MAP_CURRENT_GREEN := Color("#c5f7dc")
const MAP_REEF_MARK := Color("#e5f4c7")
const MAP_REEF_MARK_WARM := Color("#f6e7ba")
const MAP_DEPTH_LABEL := Color("#d8f2ff")
const MAP_DEPTH_LABEL_REEF := Color("#eef6c2")
const MAP_ROUTE_SELECTED := Color("#ffe070")
const MAP_ROUTE_IDLE := Color("#f6e5b0")
const MAP_ROUTE_LOCKED := Color("#a99c87")
const MAP_ROUTE_BEARING := Color("#fff0a0")
const MAP_PING_GLOW := Color("#fff2a8")
const MAP_PING_RING := Color("#ffe06d")
const MAP_PING_ARC := Color("#fff3b5")
const MAP_CHIP_FILL := Color("#f0d79a")
const MAP_CHIP_FILL_LOCKED := Color("#b9afa0")
const MAP_CHIP_BORDER_SELECTED := Color("#ffd967")
const MAP_CHIP_BORDER := Color("#5e3a1c")
const MAP_CHIP_BORDER_BOSS := Color("#d9764d")
const MAP_CHIP_HIGHLIGHT := Color("#fff1bf")
const MAP_CHIP_SHADOW_LINE := Color("#8b5b2b")
const MAP_CHIP_RIVET := Color("#6f4824")
const MAP_CHIP_TEXT := Color("#24170d")
const MAP_CHIP_TEXT_LOCKED := Color("#554b42")
const MAP_CHIP_LOCKED_TEXT := Color("#842a24")
const MAP_CHIP_BOSS_TEXT := Color("#6d2a1d")
const MAP_CHIP_LEADER := Color("#ffe8a0")

## ゲージの意味色を状態で取得（安全域=緑, 警戒=琥珀, 危険=赤）。
static func gauge_pair(level: String) -> Dictionary:
	match level:
		"amber":
			return {"from": GAUGE_AMBER, "to": GAUGE_AMBER_HI}
		"red":
			return {"from": GAUGE_RED, "to": GAUGE_RED_HI}
		_:
			return {"from": GAUGE_GREEN, "to": GAUGE_GREEN_HI}
