extends RefCounted
## ゲームの静的データカタログ（魚・釣り場・環境・レシピ・装備・船）。
# const テーブルのみを置き、ロジック関数は持たない。参照は GameData のエイリアス経由。
# 注意: FISHING_SPOTS の "required_boat_rank": 0 は GameData.NO_BOAT_RANK、
# harbor_boulder の "unlock_level": 5 は GameData.BOSS_UNLOCK_LEVEL と同値。
# これらのルール定数を変える場合は本ファイルの該当値も揃えること。

const BOSS_FIRST_CLEAR_REWARDS: Dictionary = {
	"boss_kurodai":
	{
		"money": 3000,
		"message": "港のぬしを討伐した！\n次は船を整え、南の岩礁からさらに沖の釣り場を目指そう。",
	},
	"nushi_harbor_pier":
	{
		"money": 1200,
		"message": "堤防の底主を釣り上げた！\n港内の底にひそむ古株を制した。",
	},
	"nushi_shallow_sand":
	{
		"money": 1500,
		"message": "砂底の座布団を釣り上げた！\n砂浜のかけあがりに眠る大物を制した。",
	},
	"nushi_rock_breakwater":
	{
		"money": 1800,
		"message": "磯の黒帝を釣り上げた！\n岩礁の根を支配する強敵を制した。",
	},
	"nushi_outer_tide":
	{
		"money": 1600,
		"message": "潮目の銀狼を釣り上げた！\n港外の潮を走る銀の大物を制した。",
	},
	"nushi_south_reef":
	{
		"money": 2600,
		"message": "岩窟の老王を釣り上げた！\n南の岩礁の奥に潜む重鎮を制した。",
	},
	"nushi_bluewater_route":
	{
		"money": 2400,
		"message": "回遊の大将を釣り上げた！\n外海を率いる青物の大将を制した。",
	},
	"nushi_deep_ocean":
	{
		"money": 3200,
		"message": "深淵の重鎮を釣り上げた！\n外洋の深場に潜む巨体を制した。",
	},
}

const TITLES: Array[Dictionary] = [
	{
		"id": "total_10",
		"name": "駆け出し釣り人",
		"type": "total_catches",
		"value": 10,
		"hint": "累計10匹釣る",
		"phase": "E1",
	},
	{
		"id": "total_100",
		"name": "波止場の常連",
		"type": "total_catches",
		"value": 100,
		"hint": "累計100匹釣る",
		"phase": "E1",
	},
	{
		"id": "total_500",
		"name": "海を知る者",
		"type": "total_catches",
		"value": 500,
		"hint": "累計500匹釣る",
		"phase": "E1",
	},
	{
		"id": "species_10",
		"name": "図鑑の入り口",
		"type": "species_count",
		"value": 10,
		"hint": "10種類の魚を釣る",
		"phase": "E1",
	},
	{
		"id": "species_30",
		"name": "海の収集家",
		"type": "species_count",
		"value": 30,
		"hint": "30種類の魚を釣る",
		"phase": "E1",
	},
	{
		"id": "species_50",
		"name": "海の博物学者",
		"type": "species_count",
		"value": 50,
		"hint": "50種類の魚を釣る",
		"phase": "E1",
	},
	{
		"id": "species_70",
		"name": "海の生き字引",
		"type": "species_count",
		"value": 70,
		"hint": "70種類の魚を釣る",
		"phase": "E1",
	},
	{
		"id": "aji_100",
		"name": "アジ博士",
		"type": "fish_count",
		"fish_id": "aji",
		"value": 100,
		"hint": "アジを100匹釣る",
		"phase": "E1",
	},
	{
		"id": "iwashi_100",
		"name": "イワシの群れ長",
		"type": "fish_count",
		"fish_id": "iwashi",
		"value": 100,
		"hint": "イワシを100匹釣る",
		"phase": "E1",
	},
	{
		"id": "hirame_80",
		"name": "座布団職人",
		"type": "best_size",
		"fish_id": "hirame",
		"value": 80.0,
		"hint": "ヒラメ80cm以上を釣る",
		"phase": "E1",
	},
	{
		"id": "buri_100",
		"name": "寒ブリ一本",
		"type": "best_size",
		"fish_id": "buri",
		"value": 100.0,
		"hint": "ブリ100cm以上を釣る",
		"phase": "E1",
	},
	{
		"id": "kajiki_250",
		"name": "蒼い槍の主",
		"type": "best_size",
		"fish_id": "kajiki",
		"value": 250.0,
		"hint": "カジキ250cm以上を釣る",
		"phase": "E1",
	},
	{
		"id": "spots_all",
		"name": "全釣り場制覇",
		"type": "spots_complete",
		"spot_ids": [
			"harbor_pier",
			"shallow_sand",
			"rock_breakwater",
			"outer_tide",
			"south_reef",
			"bluewater_route",
			"deep_ocean",
		],
		"hint": "通常7釣り場すべてで釣る",
		"phase": "E1",
	},
	{
		"id": "boss_kurodai",
		"name": "大岩の覇者",
		"type": "fish_caught_any",
		"fish_ids": ["boss_kurodai"],
		"hint": "港の大岩のぬしを釣る",
		"phase": "E1",
	},
	{
		"id": "level_10",
		"name": "一人前の釣り人",
		"type": "level",
		"value": 10,
		"hint": "Lv10に到達する",
		"phase": "E1",
	},
	{
		"id": "level_20",
		"name": "海のベテラン",
		"type": "level",
		"value": 20,
		"hint": "Lv20に到達する",
		"phase": "E0",
	},
	{
		"id": "level_30",
		"name": "海の頂",
		"type": "level",
		"value": 30,
		"hint": "Lv30に到達する",
		"phase": "E0",
	},
	{
		"id": "level_40",
		"name": "大海の勇者",
		"type": "level",
		"value": 40,
		"hint": "Lv40に到達する",
		"phase": "E0",
	},
	{
		"id": "level_50",
		"name": "伝説の釣り人",
		"type": "level",
		"value": 50,
		"hint": "Lv50に到達する",
		"phase": "E0",
	},
	{
		"id": "dish_10",
		"name": "港の料理人",
		"type": "dish_total",
		"value": 10,
		"hint": "料理を10回食べる",
		"phase": "E1",
	},
	{
		"id": "dish_50",
		"name": "板前級",
		"type": "dish_total",
		"value": 50,
		"hint": "料理を50回食べる",
		"phase": "E1",
	},
	{
		"id": "nushi_first",
		"name": "ヌシとの遭遇",
		"type": "fish_caught_any",
		"fish_ids": [
			"nushi_harbor_pier",
			"nushi_shallow_sand",
			"nushi_rock_breakwater",
			"nushi_outer_tide",
			"nushi_south_reef",
			"nushi_bluewater_route",
			"nushi_deep_ocean",
		],
		"hint": "いずれかのヌシを釣る",
		"phase": "E2",
	},
	{
		"id": "nushi_all",
		"name": "全ヌシ制覇",
		"type": "fish_caught_all",
		"fish_ids": [
			"nushi_harbor_pier",
			"nushi_shallow_sand",
			"nushi_rock_breakwater",
			"nushi_outer_tide",
			"nushi_south_reef",
			"nushi_bluewater_route",
			"nushi_deep_ocean",
		],
		"hint": "通常7釣り場のヌシをすべて釣る",
		"phase": "E2",
	},
	{
		"id": "quest_1",
		"name": "はじめての依頼",
		"type": "quest_completed",
		"value": 1,
		"hint": "依頼を1件達成する",
		"phase": "E3",
	},
	{
		"id": "quest_10",
		"name": "港の便利屋",
		"type": "quest_completed",
		"value": 10,
		"hint": "依頼を10件達成する",
		"phase": "E3",
	},
	{
		"id": "quest_30",
		"name": "依頼ボードの主",
		"type": "quest_completed",
		"value": 30,
		"hint": "依頼を30件達成する",
		"phase": "E3",
	},
	{
		"id": "shark_first",
		"name": "危険海域の生還者",
		"type": "fish_caught_any",
		"fish_ids": [
			"nekozame",
			"inuzame",
			"dochizame",
			"hoshizame",
			"eporetto",
			"darumazame",
			"fujikujira",
			"shumokuzame",
			"hohojirozame",
		],
		"hint": "通常サメを釣る",
		"phase": "E4",
	},
	{
		"id": "shark_nushi",
		"name": "白帝を討つ者",
		"type": "fish_caught_any",
		"fish_ids": ["nushi_danger_reef"],
		"hint": "深海の白帝を釣る",
		"phase": "E4",
	},
	{
		"id": "shark_raised_all",
		"name": "鮫使い",
		"type": "shark_bond_all",
		"shark_ids": [
			"nekozame",
			"inuzame",
			"dochizame",
			"hoshizame",
			"eporetto",
			"darumazame",
			"fujikujira",
			"shumokuzame",
			"hohojirozame",
		],
		"value": 100,
		"hint": "通常サメ9種のなつき度を100にする",
		"phase": "E10",
	},
	{
		"id": "megalodon",
		"name": "古代の海の王",
		"type": "fish_caught_any",
		"fish_ids": ["megalodon"],
		"hint": "メガロドンを釣る",
		"phase": "E10",
	},
	{
		"id": "zarigani_10",
		"name": "ザリガニ名人",
		"type": "fish_count",
		"fish_id": "zarigani",
		"value": 10,
		"hint": "ザリガニを10匹釣る",
		"phase": "E8",
	},
]

const FISH: Dictionary = {
	"aji":
	{
		"id": "aji",
		"name": "アジ",
		"rarity": "コモン",
		"min_level": 1,
		"boss": false,
		"weight": 32.0,
		"size_min": 12.0,
		"size_max": 40.0,
		"sell_price": 120,
		"food_exp": 20,
		"stamina": 42.0,
		"power": 0.62,
		"speed": 1.10,
		"start_distance": 20.0,
		"start_depth": 7.0,
		"color": "#9cc9d8",
		"habitat": "港内・堤防周り",
		"behavior": "小刻みに方向転換する。初心者向け。",
		"fish_no": "No.001",
		"preferred_bait": "アミエビ",
		"visual_scale": 0.82,
		"line_anchor_x": 0.455,
		"line_anchor_y": 0.02,
		"motion": {"wave_amp": 0.026, "wave_freq": 4.8, "dash_shift": 0.040, "turn_shift": 0.060, "dive_shift": 0.020, "jitter": 0.006, "depth_bias": 0.0},
		"action_profile": {"dash": 0.22, "dive": 0.08, "turn": 0.45, "rest": 0.25},
		"action_messages": {"dash": "アジが小さく走った！ テンションを保とう！", "dive": "アジが少し潜る！ 焦らず合わせよう。", "turn": "アジが素早く向きを変えた！", "rest": "アジの動きが緩んだ。巻き上げよう！"},
	},
	"mejina":
	{
		"id": "mejina",
		"name": "メジナ",
		"rarity": "コモン",
		"min_level": 1,
		"boss": false,
		"weight": 24.0,
		"size_min": 20.0,
		"size_max": 50.0,
		"sell_price": 190,
		"food_exp": 28,
		"stamina": 58.0,
		"power": 0.82,
		"speed": 0.88,
		"start_distance": 23.0,
		"start_depth": 9.0,
		"color": "#4b6875",
		"habitat": "磯・消波ブロック周り",
		"behavior": "根へ向かって潜る。糸を出す判断が必要。",
		"fish_no": "No.002",
		"preferred_bait": "オキアミ",
		"visual_scale": 0.96,
		"line_anchor_x": 0.420,
		"line_anchor_y": 0.04,
		"motion": {"wave_amp": 0.018, "wave_freq": 2.6, "dash_shift": 0.038, "turn_shift": 0.040, "dive_shift": 0.050, "jitter": 0.002, "depth_bias": 0.020},
		"action_profile": {"dash": 0.20, "dive": 0.40, "turn": 0.22, "rest": 0.18},
		"action_messages": {"dash": "メジナが根へ走った！ 無理に巻かず耐えよう！", "dive": "メジナが深く潜る！ 糸を出して耐えよう！", "turn": "メジナが足元で反転した。テンション注意！", "rest": "メジナの抵抗が弱まった。今が巻き時だ！"},
	},
	"kasago":
	{
		"id": "kasago",
		"name": "カサゴ",
		"rarity": "コモン",
		"min_level": 1,
		"boss": false,
		"weight": 20.0,
		"size_min": 12.0,
		"size_max": 30.0,
		"sell_price": 210,
		"food_exp": 30,
		"stamina": 50.0,
		"power": 0.75,
		"speed": 0.64,
		"start_distance": 19.0,
		"start_depth": 12.0,
		"color": "#b85c42",
		"habitat": "岩礁・海底付近",
		"behavior": "底へ張り付く。短く強い突進を行う。",
		"fish_no": "No.003",
		"preferred_bait": "イソメ",
		"visual_scale": 0.78,
		"line_anchor_x": 0.400,
		"line_anchor_y": 0.02,
		"motion": {"wave_amp": 0.010, "wave_freq": 1.7, "dash_shift": 0.030, "turn_shift": 0.026, "dive_shift": 0.065, "jitter": 0.002, "depth_bias": 0.060},
		"action_profile": {"dash": 0.36, "dive": 0.34, "turn": 0.14, "rest": 0.16},
		"action_messages": {"dash": "カサゴが岩陰へ突っ込む！ 竿を立てて耐えよう！", "dive": "カサゴが底へ張り付く！ 糸を出して粘ろう！", "turn": "カサゴが短く向きを変えた。", "rest": "カサゴが浮いた。巻き上げるチャンス！"},
	},
	"isaki":
	{
		"id": "isaki",
		"name": "イサキ",
		"rarity": "アンコモン",
		"min_level": 2,
		"boss": false,
		"weight": 15.0,
		"size_min": 20.0,
		"size_max": 45.0,
		"sell_price": 320,
		"food_exp": 42,
		"stamina": 72.0,
		"power": 0.98,
		"speed": 0.95,
		"start_distance": 27.0,
		"start_depth": 13.0,
		"color": "#8da39d",
		"habitat": "沖の岩礁帯",
		"behavior": "一定間隔で長く走る。体力管理が重要。",
		"fish_no": "No.004",
		"preferred_bait": "オキアミ",
		"visual_scale": 0.94,
		"line_anchor_x": 0.440,
		"line_anchor_y": 0.02,
		"motion": {"wave_amp": 0.020, "wave_freq": 3.0, "dash_shift": 0.055, "turn_shift": 0.040, "dive_shift": 0.034, "jitter": 0.003, "depth_bias": 0.010},
		"action_profile": {"dash": 0.38, "dive": 0.20, "turn": 0.22, "rest": 0.20},
		"action_messages": {"dash": "イサキが長く走る！ 巻きすぎず追従しよう！", "dive": "イサキが沖の根へ潜る！", "turn": "イサキが群れのように向きを変えた。", "rest": "イサキの走りが止まった。巻き上げよう！"},
	},
	"saba":
	{
		"id": "saba",
		"name": "サバ",
		"rarity": "アンコモン",
		"min_level": 3,
		"boss": false,
		"weight": 9.0,
		"size_min": 25.0,
		"size_max": 50.0,
		"sell_price": 390,
		"food_exp": 50,
		"stamina": 84.0,
		"power": 1.05,
		"speed": 1.35,
		"start_distance": 30.0,
		"start_depth": 10.0,
		"color": "#6a91a5",
		"habitat": "港外・潮通しのよい場所",
		"behavior": "横方向へ高速で走り続ける。",
		"fish_no": "No.005",
		"preferred_bait": "小魚",
		"visual_scale": 0.98,
		"line_anchor_x": 0.455,
		"line_anchor_y": 0.01,
		"motion": {"wave_amp": 0.030, "wave_freq": 5.2, "dash_shift": 0.080, "turn_shift": 0.045, "dive_shift": 0.022, "jitter": 0.005, "depth_bias": -0.010},
		"action_profile": {"dash": 0.52, "dive": 0.10, "turn": 0.22, "rest": 0.16},
		"action_messages": {"dash": "サバが横へ一気に走った！ ラインを出して耐えよう！", "dive": "サバが少し潜る！ 速度に注意！", "turn": "サバが高速で反転した！", "rest": "サバの走りが緩んだ。巻き時だ！"},
	},
	"suzuki":
	{
		"id": "suzuki",
		"name": "スズキ",
		"rarity": "アンコモン",
		"min_level": 3,
		"boss": false,
		"weight": 8.0,
		"size_min": 30.0,
		"size_max": 85.0,
		"sell_price": 520,
		"food_exp": 62,
		"stamina": 92.0,
		"power": 1.12,
		"speed": 1.12,
		"start_distance": 33.0,
		"start_depth": 8.0,
		"color": "#9fa69a",
		"habitat": "河口・港外の潮目",
		"behavior": "水面近くで反転し、長く走る。",
		"fish_no": "No.006",
		"preferred_bait": "小魚",
		"visual_scale": 1.10,
		"line_anchor_x": 0.445,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.020, "wave_freq": 2.8, "dash_shift": 0.065, "turn_shift": 0.070, "dive_shift": 0.018, "jitter": 0.002, "depth_bias": -0.030},
		"action_profile": {"dash": 0.38, "dive": 0.12, "turn": 0.36, "rest": 0.14},
		"action_messages": {"dash": "スズキが水面近くを長く走る！", "dive": "スズキが潮目の下へ潜る！", "turn": "スズキが大きく反転した！ テンションの変化に注意！", "rest": "スズキの動きが止まった。距離を詰めよう！"},
	},
	"madai":
	{
		"id": "madai",
		"name": "マダイ",
		"rarity": "レア",
		"min_level": 4,
		"boss": false,
		"weight": 5.0,
		"size_min": 25.0,
		"size_max": 85.0,
		"sell_price": 760,
		"food_exp": 86,
		"stamina": 118.0,
		"power": 1.24,
		"speed": 0.96,
		"start_distance": 35.0,
		"start_depth": 16.0,
		"color": "#d77b76",
		"habitat": "沖の岩礁・砂地の境目",
		"behavior": "重く首を振りながら底へ向かう。",
		"fish_no": "No.007",
		"preferred_bait": "オキアミ",
		"visual_scale": 1.08,
		"line_anchor_x": 0.420,
		"line_anchor_y": 0.04,
		"motion": {"wave_amp": 0.013, "wave_freq": 2.0, "dash_shift": 0.040, "turn_shift": 0.030, "dive_shift": 0.058, "jitter": 0.001, "depth_bias": 0.025},
		"action_profile": {"dash": 0.24, "dive": 0.38, "turn": 0.18, "rest": 0.20},
		"action_messages": {"dash": "マダイが重く首を振る！ 無理に巻かず耐えよう！", "dive": "マダイが底へ向かう！ 糸を出して粘ろう！", "turn": "マダイがゆっくり反転した。", "rest": "マダイの重みが抜けた。巻き上げよう！"},
	},
	"hirame":
	{
		"id": "hirame",
		"name": "ヒラメ",
		"rarity": "レア",
		"min_level": 4,
		"boss": false,
		"weight": 4.5,
		"size_min": 30.0,
		"size_max": 85.0,
		"sell_price": 820,
		"food_exp": 90,
		"stamina": 110.0,
		"power": 1.18,
		"speed": 0.78,
		"start_distance": 31.0,
		"start_depth": 14.0,
		"color": "#7b6b42",
		"habitat": "砂地・かけあがり",
		"behavior": "底に張り付き、急に横へ走る。",
		"fish_no": "No.008",
		"preferred_bait": "小魚",
		"visual_scale": 1.04,
		"line_anchor_x": 0.430,
		"line_anchor_y": 0.05,
		"motion": {"wave_amp": 0.008, "wave_freq": 1.5, "dash_shift": 0.055, "turn_shift": 0.022, "dive_shift": 0.060, "jitter": 0.001, "depth_bias": 0.070},
		"action_profile": {"dash": 0.30, "dive": 0.42, "turn": 0.12, "rest": 0.16},
		"action_messages": {"dash": "ヒラメが底から横へ走った！", "dive": "ヒラメが砂地へ張り付く！ 焦らず耐えよう！", "turn": "ヒラメが低く向きを変えた。", "rest": "ヒラメが浮いた。巻き上げるチャンス！"},
	},
	"kawahagi":
	{
		"id": "kawahagi",
		"name": "カワハギ",
		"rarity": "アンコモン",
		"min_level": 2,
		"boss": false,
		"weight": 10.0,
		"size_min": 12.0,
		"size_max": 30.0,
		"sell_price": 360,
		"food_exp": 46,
		"stamina": 68.0,
		"power": 0.88,
		"speed": 1.02,
		"start_distance": 24.0,
		"start_depth": 11.0,
		"color": "#8d7b55",
		"habitat": "堤防際・砂まじりの岩場",
		"behavior": "細かく逃げ回り、テンションを揺さぶる。",
		"fish_no": "No.009",
		"preferred_bait": "アサリ",
		"visual_scale": 0.78,
		"line_anchor_x": 0.380,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.024, "wave_freq": 6.2, "dash_shift": 0.034, "turn_shift": 0.070, "dive_shift": 0.020, "jitter": 0.012, "depth_bias": 0.010},
		"action_profile": {"dash": 0.18, "dive": 0.12, "turn": 0.50, "rest": 0.20},
		"action_messages": {"dash": "カワハギが細かく逃げた！ テンションを揺さぶられる！", "dive": "カワハギが足元へ潜る！", "turn": "カワハギが小刻みに方向転換した！", "rest": "カワハギの動きが止まった。巻き上げよう！"},
	},
	"iwashi":
	{
		"id": "iwashi",
		"name": "イワシ",
		"rarity": "コモン",
		"min_level": 1,
		"boss": false,
		"weight": 26.0,
		"size_min": 10.0,
		"size_max": 22.0,
		"sell_price": 90,
		"food_exp": 16,
		"stamina": 34.0,
		"power": 0.48,
		"speed": 1.28,
		"start_distance": 18.0,
		"start_depth": 6.0,
		"color": "#8fb7c8",
		"habitat": "港内・表層の群れ",
		"behavior": "群れで小刻みに泳ぎ、細かく向きを変える。",
		"fish_no": "No.010",
		"preferred_bait": "アミエビ",
		"visual_scale": 0.68,
		"line_anchor_x": 0.455,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.028, "wave_freq": 6.0, "dash_shift": 0.036, "turn_shift": 0.070, "dive_shift": 0.014, "jitter": 0.012, "depth_bias": -0.030},
		"action_profile": {"dash": 0.20, "dive": 0.06, "turn": 0.56, "rest": 0.18},
		"action_messages": {"dash": "イワシが群れに戻ろうと走る！", "dive": "イワシが少し潜った。", "turn": "イワシが小刻みに反転した！", "rest": "イワシの動きが緩んだ。巻き上げよう！"},
	},
	"shirogisu":
	{
		"id": "shirogisu",
		"name": "シロギス",
		"rarity": "コモン",
		"min_level": 1,
		"boss": false,
		"weight": 22.0,
		"size_min": 12.0,
		"size_max": 27.0,
		"sell_price": 130,
		"food_exp": 22,
		"stamina": 40.0,
		"power": 0.58,
		"speed": 1.05,
		"start_distance": 21.0,
		"start_depth": 8.0,
		"color": "#d8c29a",
		"habitat": "砂浜・浅いかけあがり",
		"behavior": "砂地を軽く走る。引きは素直で扱いやすい。",
		"fish_no": "No.011",
		"preferred_bait": "イソメ",
		"visual_scale": 0.72,
		"line_anchor_x": 0.455,
		"line_anchor_y": 0.01,
		"motion": {"wave_amp": 0.020, "wave_freq": 3.8, "dash_shift": 0.038, "turn_shift": 0.045, "dive_shift": 0.024, "jitter": 0.004, "depth_bias": 0.010},
		"action_profile": {"dash": 0.28, "dive": 0.18, "turn": 0.30, "rest": 0.24},
		"action_messages": {"dash": "シロギスが砂地を軽く走った！", "dive": "シロギスが砂地へ潜る！", "turn": "シロギスが向きを変えた。", "rest": "シロギスの動きが止まった。巻き上げよう！"},
	},
	"mebaru":
	{
		"id": "mebaru",
		"name": "メバル",
		"rarity": "コモン",
		"min_level": 2,
		"boss": false,
		"weight": 18.0,
		"size_min": 12.0,
		"size_max": 30.0,
		"sell_price": 180,
		"food_exp": 29,
		"stamina": 52.0,
		"power": 0.74,
		"speed": 0.78,
		"start_distance": 20.0,
		"start_depth": 10.0,
		"color": "#9b4c38",
		"habitat": "岩場・藻場の陰",
		"behavior": "岩陰へ潜り、短く粘る。",
		"fish_no": "No.012",
		"preferred_bait": "イソメ",
		"visual_scale": 0.76,
		"line_anchor_x": 0.405,
		"line_anchor_y": 0.02,
		"motion": {"wave_amp": 0.012, "wave_freq": 2.0, "dash_shift": 0.032, "turn_shift": 0.030, "dive_shift": 0.055, "jitter": 0.002, "depth_bias": 0.045},
		"action_profile": {"dash": 0.28, "dive": 0.36, "turn": 0.18, "rest": 0.18},
		"action_messages": {"dash": "メバルが岩陰へ走った！", "dive": "メバルが下へ潜る！ 根に入られないよう耐えよう！", "turn": "メバルが短く向きを変えた。", "rest": "メバルが浮いた。巻き上げよう！"},
	},
	"ainame":
	{
		"id": "ainame",
		"name": "アイナメ",
		"rarity": "アンコモン",
		"min_level": 2,
		"boss": false,
		"weight": 14.0,
		"size_min": 20.0,
		"size_max": 50.0,
		"sell_price": 300,
		"food_exp": 42,
		"stamina": 70.0,
		"power": 0.95,
		"speed": 0.72,
		"start_distance": 24.0,
		"start_depth": 13.0,
		"color": "#7a6b3e",
		"habitat": "岩礁・消波ブロックの底",
		"behavior": "重く底へ向かう。根に潜る前に止めたい。",
		"fish_no": "No.013",
		"preferred_bait": "イソメ",
		"visual_scale": 0.92,
		"line_anchor_x": 0.425,
		"line_anchor_y": 0.03,
		"motion": {"wave_amp": 0.010, "wave_freq": 1.8, "dash_shift": 0.034, "turn_shift": 0.026, "dive_shift": 0.065, "jitter": 0.001, "depth_bias": 0.060},
		"action_profile": {"dash": 0.24, "dive": 0.46, "turn": 0.12, "rest": 0.18},
		"action_messages": {"dash": "アイナメが根へ走る！ 竿を立てて耐えよう！", "dive": "アイナメが底へ潜る！ 糸を出して粘ろう！", "turn": "アイナメが重く向きを変えた。", "rest": "アイナメが浮いた。巻き上げるチャンス！"},
	},
	"bora":
	{
		"id": "bora",
		"name": "ボラ",
		"rarity": "アンコモン",
		"min_level": 2,
		"boss": false,
		"weight": 12.0,
		"size_min": 30.0,
		"size_max": 70.0,
		"sell_price": 260,
		"food_exp": 38,
		"stamina": 82.0,
		"power": 0.92,
		"speed": 1.18,
		"start_distance": 29.0,
		"start_depth": 7.0,
		"color": "#9aa998",
		"habitat": "港内・河口の表層",
		"behavior": "水面近くを大きく反転しながら走る。",
		"fish_no": "No.014",
		"preferred_bait": "練りエサ",
		"visual_scale": 1.02,
		"line_anchor_x": 0.445,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.024, "wave_freq": 3.4, "dash_shift": 0.060, "turn_shift": 0.075, "dive_shift": 0.015, "jitter": 0.004, "depth_bias": -0.040},
		"action_profile": {"dash": 0.32, "dive": 0.08, "turn": 0.42, "rest": 0.18},
		"action_messages": {"dash": "ボラが水面近くを走った！", "dive": "ボラが少し沈んだ。", "turn": "ボラが大きく反転した！ テンション注意！", "rest": "ボラの動きが鈍った。距離を詰めよう！"},
	},
	"kamasu":
	{
		"id": "kamasu",
		"name": "カマス",
		"rarity": "アンコモン",
		"min_level": 3,
		"boss": false,
		"weight": 10.0,
		"size_min": 20.0,
		"size_max": 40.0,
		"sell_price": 340,
		"food_exp": 46,
		"stamina": 66.0,
		"power": 0.86,
		"speed": 1.48,
		"start_distance": 30.0,
		"start_depth": 8.0,
		"color": "#9fb2b2",
		"habitat": "港外・常夜灯周り",
		"behavior": "細長い体で鋭く横へ走る。",
		"fish_no": "No.015",
		"preferred_bait": "小魚",
		"visual_scale": 0.86,
		"line_anchor_x": 0.470,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.027, "wave_freq": 5.6, "dash_shift": 0.082, "turn_shift": 0.050, "dive_shift": 0.018, "jitter": 0.006, "depth_bias": -0.020},
		"action_profile": {"dash": 0.56, "dive": 0.08, "turn": 0.22, "rest": 0.14},
		"action_messages": {"dash": "カマスが鋭く横へ走った！", "dive": "カマスが少し潜る！", "turn": "カマスが素早く向きを変えた！", "rest": "カマスの走りが止まった。巻き上げよう！"},
	},
	"kochi":
	{
		"id": "kochi",
		"name": "コチ",
		"rarity": "アンコモン",
		"min_level": 3,
		"boss": false,
		"weight": 8.0,
		"size_min": 30.0,
		"size_max": 65.0,
		"sell_price": 470,
		"food_exp": 58,
		"stamina": 88.0,
		"power": 1.02,
		"speed": 0.70,
		"start_distance": 27.0,
		"start_depth": 14.0,
		"color": "#7f6a48",
		"habitat": "砂地・かけあがりの底",
		"behavior": "底に張り付き、突然横へ走る。",
		"fish_no": "No.016",
		"preferred_bait": "小魚",
		"visual_scale": 1.00,
		"line_anchor_x": 0.430,
		"line_anchor_y": 0.04,
		"motion": {"wave_amp": 0.008, "wave_freq": 1.5, "dash_shift": 0.052, "turn_shift": 0.020, "dive_shift": 0.066, "jitter": 0.001, "depth_bias": 0.075},
		"action_profile": {"dash": 0.32, "dive": 0.42, "turn": 0.10, "rest": 0.16},
		"action_messages": {"dash": "コチが砂地から横へ走った！", "dive": "コチが底へ張り付く！ 焦らず耐えよう！", "turn": "コチが低く向きを変えた。", "rest": "コチが浮いた。巻き上げよう！"},
	},
	"tachiuo":
	{
		"id": "tachiuo",
		"name": "タチウオ",
		"rarity": "レア",
		"min_level": 4,
		"boss": false,
		"weight": 6.0,
		"size_min": 70.0,
		"size_max": 130.0,
		"sell_price": 680,
		"food_exp": 78,
		"stamina": 90.0,
		"power": 1.08,
		"speed": 1.20,
		"start_distance": 34.0,
		"start_depth": 15.0,
		"color": "#b7c8d3",
		"habitat": "沖の深場・夜の港外",
		"behavior": "銀色の体をくねらせ、上下に鋭く動く。",
		"fish_no": "No.017",
		"preferred_bait": "小魚",
		"visual_scale": 1.04,
		"line_anchor_x": 0.465,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.032, "wave_freq": 4.4, "dash_shift": 0.060, "turn_shift": 0.050, "dive_shift": 0.050, "jitter": 0.005, "depth_bias": 0.030},
		"action_profile": {"dash": 0.34, "dive": 0.28, "turn": 0.24, "rest": 0.14},
		"action_messages": {"dash": "タチウオが銀色の体で走った！", "dive": "タチウオが深場へ沈む！", "turn": "タチウオが鋭く反転した！", "rest": "タチウオの動きが止まった。巻き上げよう！"},
	},
	"ishidai":
	{
		"id": "ishidai",
		"name": "イシダイ",
		"rarity": "レア",
		"min_level": 4,
		"boss": false,
		"weight": 5.5,
		"size_min": 25.0,
		"size_max": 65.0,
		"sell_price": 780,
		"food_exp": 88,
		"stamina": 118.0,
		"power": 1.30,
		"speed": 0.82,
		"start_distance": 32.0,
		"start_depth": 16.0,
		"color": "#5c6268",
		"habitat": "磯・岩礁の深み",
		"behavior": "強い歯で根周りへ突っ込み、重く粘る。",
		"fish_no": "No.018",
		"preferred_bait": "貝",
		"visual_scale": 0.98,
		"line_anchor_x": 0.420,
		"line_anchor_y": 0.03,
		"motion": {"wave_amp": 0.012, "wave_freq": 2.0, "dash_shift": 0.050, "turn_shift": 0.030, "dive_shift": 0.060, "jitter": 0.001, "depth_bias": 0.045},
		"action_profile": {"dash": 0.34, "dive": 0.34, "turn": 0.12, "rest": 0.20},
		"action_messages": {"dash": "イシダイが岩場へ突っ込む！", "dive": "イシダイが深く潜る！ 糸を出して耐えよう！", "turn": "イシダイが重く反転した。", "rest": "イシダイの抵抗が弱まった。巻き時だ！"},
	},
	"akahata":
	{
		"id": "akahata",
		"name": "アカハタ",
		"rarity": "レア",
		"min_level": 4,
		"boss": false,
		"weight": 5.0,
		"size_min": 20.0,
		"size_max": 40.0,
		"sell_price": 720,
		"food_exp": 82,
		"stamina": 100.0,
		"power": 1.12,
		"speed": 0.78,
		"start_distance": 29.0,
		"start_depth": 17.0,
		"color": "#c85a34",
		"habitat": "南の岩礁・サンゴ根",
		"behavior": "岩陰へ戻ろうとする赤い根魚。",
		"fish_no": "No.019",
		"preferred_bait": "小魚",
		"visual_scale": 0.88,
		"line_anchor_x": 0.410,
		"line_anchor_y": 0.03,
		"motion": {"wave_amp": 0.010, "wave_freq": 1.8, "dash_shift": 0.042, "turn_shift": 0.028, "dive_shift": 0.064, "jitter": 0.001, "depth_bias": 0.070},
		"action_profile": {"dash": 0.30, "dive": 0.42, "turn": 0.12, "rest": 0.16},
		"action_messages": {"dash": "アカハタが岩陰へ走った！", "dive": "アカハタが根へ潜る！", "turn": "アカハタが短く反転した。", "rest": "アカハタが浮いた。巻き上げよう！"},
	},
	"fuefukidai":
	{
		"id": "fuefukidai",
		"name": "フエフキダイ",
		"rarity": "レア",
		"min_level": 5,
		"boss": false,
		"weight": 4.2,
		"size_min": 30.0,
		"size_max": 70.0,
		"sell_price": 860,
		"food_exp": 96,
		"stamina": 126.0,
		"power": 1.22,
		"speed": 0.92,
		"start_distance": 35.0,
		"start_depth": 18.0,
		"color": "#d3928d",
		"habitat": "南の沖根・砂地の境目",
		"behavior": "重く首を振りながら沖へ走る。",
		"fish_no": "No.020",
		"preferred_bait": "オキアミ",
		"visual_scale": 1.06,
		"line_anchor_x": 0.420,
		"line_anchor_y": 0.04,
		"motion": {"wave_amp": 0.014, "wave_freq": 2.1, "dash_shift": 0.046, "turn_shift": 0.032, "dive_shift": 0.058, "jitter": 0.001, "depth_bias": 0.040},
		"action_profile": {"dash": 0.30, "dive": 0.34, "turn": 0.16, "rest": 0.20},
		"action_messages": {"dash": "フエフキダイが沖へ走る！", "dive": "フエフキダイが底へ向かう！", "turn": "フエフキダイが重く反転した。", "rest": "フエフキダイの動きが鈍った。巻き時だ！"},
	},
	"aobudai":
	{
		"id": "aobudai",
		"name": "アオブダイ",
		"rarity": "レア",
		"min_level": 5,
		"boss": false,
		"weight": 3.8,
		"size_min": 35.0,
		"size_max": 80.0,
		"sell_price": 900,
		"food_exp": 104,
		"stamina": 132.0,
		"power": 1.18,
		"speed": 0.86,
		"start_distance": 34.0,
		"start_depth": 12.0,
		"color": "#2e9db0",
		"habitat": "サンゴ礁・浅い岩礁帯",
		"behavior": "大きな体でゆっくり反転し、岩場へ寄る。",
		"fish_no": "No.021",
		"preferred_bait": "貝",
		"visual_scale": 1.10,
		"line_anchor_x": 0.405,
		"line_anchor_y": 0.03,
		"motion": {"wave_amp": 0.012, "wave_freq": 1.9, "dash_shift": 0.038, "turn_shift": 0.048, "dive_shift": 0.050, "jitter": 0.001, "depth_bias": 0.010},
		"action_profile": {"dash": 0.20, "dive": 0.30, "turn": 0.30, "rest": 0.20},
		"action_messages": {"dash": "アオブダイが重く走る！", "dive": "アオブダイが岩場へ潜る！", "turn": "アオブダイが大きく反転した。", "rest": "アオブダイの動きが止まった。巻き上げよう！"},
	},
	"kanpachi":
	{
		"id": "kanpachi",
		"name": "カンパチ",
		"rarity": "レア",
		"min_level": 6,
		"boss": false,
		"weight": 3.3,
		"size_min": 40.0,
		"size_max": 120.0,
		"sell_price": 1050,
		"food_exp": 118,
		"stamina": 142.0,
		"power": 1.28,
		"speed": 1.35,
		"start_distance": 40.0,
		"start_depth": 14.0,
		"color": "#7f9aa0",
		"habitat": "沖の潮目・回遊ルート",
		"behavior": "青物らしく長く横へ走る。",
		"fish_no": "No.022",
		"preferred_bait": "小魚",
		"visual_scale": 1.14,
		"line_anchor_x": 0.445,
		"line_anchor_y": 0.01,
		"motion": {"wave_amp": 0.026, "wave_freq": 4.8, "dash_shift": 0.088, "turn_shift": 0.048, "dive_shift": 0.030, "jitter": 0.004, "depth_bias": 0.000},
		"action_profile": {"dash": 0.56, "dive": 0.14, "turn": 0.16, "rest": 0.14},
		"action_messages": {"dash": "カンパチが沖へ一気に走る！ ラインを出して耐えよう！", "dive": "カンパチが潮目の下へ潜る！", "turn": "カンパチが高速で向きを変えた！", "rest": "カンパチの走りが緩んだ。巻き時だ！"},
	},
	"buri":
	{
		"id": "buri",
		"name": "ブリ",
		"rarity": "レア",
		"min_level": 6,
		"boss": false,
		"weight": 3.0,
		"size_min": 55.0,
		"size_max": 110.0,
		"sell_price": 1180,
		"food_exp": 130,
		"stamina": 158.0,
		"power": 1.38,
		"speed": 1.20,
		"start_distance": 42.0,
		"start_depth": 15.0,
		"color": "#6f9097",
		"habitat": "外海・潮通しのよい沖",
		"behavior": "重い体で長く走り、巻き上げを拒む。",
		"fish_no": "No.023",
		"preferred_bait": "小魚",
		"visual_scale": 1.18,
		"line_anchor_x": 0.440,
		"line_anchor_y": 0.01,
		"motion": {"wave_amp": 0.020, "wave_freq": 3.4, "dash_shift": 0.078, "turn_shift": 0.040, "dive_shift": 0.038, "jitter": 0.002, "depth_bias": 0.010},
		"action_profile": {"dash": 0.50, "dive": 0.22, "turn": 0.12, "rest": 0.16},
		"action_messages": {"dash": "ブリが外海へ走る！ 無理に止めず耐えよう！", "dive": "ブリが深く沈む！", "turn": "ブリが重く向きを変えた。", "rest": "ブリの走りが止まった。巻き上げよう！"},
	},
	"katsuo":
	{
		"id": "katsuo",
		"name": "カツオ",
		"rarity": "レア",
		"min_level": 7,
		"boss": false,
		"weight": 2.8,
		"size_min": 40.0,
		"size_max": 80.0,
		"sell_price": 1250,
		"food_exp": 136,
		"stamina": 136.0,
		"power": 1.22,
		"speed": 1.60,
		"start_distance": 44.0,
		"start_depth": 12.0,
		"color": "#526d8c",
		"habitat": "外海表層・潮目",
		"behavior": "表層を高速で走り続ける。",
		"fish_no": "No.024",
		"preferred_bait": "小魚",
		"visual_scale": 1.06,
		"line_anchor_x": 0.455,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.030, "wave_freq": 5.8, "dash_shift": 0.096, "turn_shift": 0.050, "dive_shift": 0.020, "jitter": 0.006, "depth_bias": -0.020},
		"action_profile": {"dash": 0.64, "dive": 0.08, "turn": 0.16, "rest": 0.12},
		"action_messages": {"dash": "カツオが表層を猛スピードで走った！", "dive": "カツオが少し沈む！", "turn": "カツオが高速で反転した！", "rest": "カツオの速度が落ちた。巻き時だ！"},
	},
	"shiira":
	{
		"id": "shiira",
		"name": "シイラ",
		"rarity": "レア",
		"min_level": 7,
		"boss": false,
		"weight": 2.5,
		"size_min": 60.0,
		"size_max": 140.0,
		"sell_price": 1380,
		"food_exp": 148,
		"stamina": 146.0,
		"power": 1.25,
		"speed": 1.45,
		"start_distance": 45.0,
		"start_depth": 6.0,
		"color": "#a6bd27",
		"habitat": "外海表層・流れ藻周り",
		"behavior": "水面近くを派手に跳ねるように走る。",
		"fish_no": "No.025",
		"preferred_bait": "小魚",
		"visual_scale": 1.20,
		"line_anchor_x": 0.440,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.034, "wave_freq": 4.9, "dash_shift": 0.086, "turn_shift": 0.065, "dive_shift": 0.012, "jitter": 0.006, "depth_bias": -0.060},
		"action_profile": {"dash": 0.48, "dive": 0.06, "turn": 0.34, "rest": 0.12},
		"action_messages": {"dash": "シイラが水面近くを派手に走る！", "dive": "シイラが一瞬沈む！", "turn": "シイラが大きく跳ねるように反転した！", "rest": "シイラの勢いが落ちた。巻き上げよう！"},
	},
	"kue":
	{
		"id": "kue",
		"name": "クエ",
		"rarity": "レア",
		"min_level": 8,
		"boss": false,
		"weight": 2.0,
		"size_min": 50.0,
		"size_max": 130.0,
		"sell_price": 1650,
		"food_exp": 165,
		"stamina": 176.0,
		"power": 1.48,
		"speed": 0.62,
		"start_distance": 36.0,
		"start_depth": 20.0,
		"color": "#6b5b43",
		"habitat": "深い岩礁・大岩の穴",
		"behavior": "圧倒的な重さで底へ潜り続ける。",
		"fish_no": "No.026",
		"preferred_bait": "小魚",
		"visual_scale": 1.18,
		"line_anchor_x": 0.405,
		"line_anchor_y": 0.04,
		"motion": {"wave_amp": 0.007, "wave_freq": 1.4, "dash_shift": 0.034, "turn_shift": 0.020, "dive_shift": 0.085, "jitter": 0.001, "depth_bias": 0.090},
		"action_profile": {"dash": 0.18, "dive": 0.58, "turn": 0.06, "rest": 0.18},
		"action_messages": {"dash": "クエが大岩へ突っ込む！", "dive": "クエが底へ沈む！ 糸を出して耐えよう！", "turn": "クエが重く体を返した。", "rest": "クエの重みが少し抜けた。巻き上げよう！"},
	},
	"hiramasa":
	{
		"id": "hiramasa",
		"name": "ヒラマサ",
		"rarity": "レア",
		"min_level": 8,
		"boss": false,
		"weight": 1.8,
		"size_min": 60.0,
		"size_max": 140.0,
		"sell_price": 1720,
		"food_exp": 170,
		"stamina": 168.0,
		"power": 1.42,
		"speed": 1.42,
		"start_distance": 46.0,
		"start_depth": 15.0,
		"color": "#7a9896",
		"habitat": "外海の岩礁帯・潮目",
		"behavior": "鋭い突進で根へ向かう上位青物。",
		"fish_no": "No.027",
		"preferred_bait": "小魚",
		"visual_scale": 1.18,
		"line_anchor_x": 0.445,
		"line_anchor_y": 0.01,
		"motion": {"wave_amp": 0.024, "wave_freq": 4.6, "dash_shift": 0.092, "turn_shift": 0.044, "dive_shift": 0.040, "jitter": 0.003, "depth_bias": 0.005},
		"action_profile": {"dash": 0.58, "dive": 0.20, "turn": 0.10, "rest": 0.12},
		"action_messages": {"dash": "ヒラマサが根へ向かって突進する！", "dive": "ヒラマサが深く入る！ ラインを出して耐えよう！", "turn": "ヒラマサが鋭く反転した！", "rest": "ヒラマサの走りが止まった。今が巻き時だ！"},
	},
	"rouninaji":
	{
		"id": "rouninaji",
		"name": "ロウニンアジ",
		"rarity": "レア",
		"min_level": 9,
		"boss": false,
		"weight": 1.4,
		"size_min": 60.0,
		"size_max": 160.0,
		"sell_price": 2100,
		"food_exp": 190,
		"stamina": 186.0,
		"power": 1.55,
		"speed": 1.30,
		"start_distance": 48.0,
		"start_depth": 16.0,
		"color": "#6d7d85",
		"habitat": "南の外洋・リーフエッジ",
		"behavior": "強烈な横走りと反転でラインを削る。",
		"fish_no": "No.028",
		"preferred_bait": "小魚",
		"visual_scale": 1.20,
		"line_anchor_x": 0.415,
		"line_anchor_y": 0.02,
		"motion": {"wave_amp": 0.020, "wave_freq": 3.8, "dash_shift": 0.090, "turn_shift": 0.060, "dive_shift": 0.052, "jitter": 0.002, "depth_bias": 0.025},
		"action_profile": {"dash": 0.50, "dive": 0.24, "turn": 0.16, "rest": 0.10},
		"action_messages": {"dash": "ロウニンアジが外洋へ突っ走る！", "dive": "ロウニンアジがリーフ際へ潜る！", "turn": "ロウニンアジが強烈に反転した！", "rest": "ロウニンアジの走りが一瞬止まった。巻け！"},
	},
	"kajiki":
	{
		"id": "kajiki",
		"name": "カジキ",
		"rarity": "レア",
		"min_level": 10,
		"boss": false,
		"weight": 1.0,
		"size_min": 150.0,
		"size_max": 330.0,
		"sell_price": 2800,
		"food_exp": 220,
		"stamina": 210.0,
		"power": 1.62,
		"speed": 1.48,
		"start_distance": 55.0,
		"start_depth": 18.0,
		"color": "#304b78",
		"habitat": "外洋の深い潮目",
		"behavior": "巨大な体で外洋へ走り、長期戦になる。",
		"fish_no": "No.029",
		"preferred_bait": "大型ルアー",
		"visual_scale": 1.26,
		"line_anchor_x": 0.485,
		"line_anchor_y": -0.01,
		"motion": {"wave_amp": 0.024, "wave_freq": 3.2, "dash_shift": 0.100, "turn_shift": 0.044, "dive_shift": 0.050, "jitter": 0.001, "depth_bias": 0.020},
		"action_profile": {"dash": 0.58, "dive": 0.22, "turn": 0.08, "rest": 0.12},
		"action_messages": {"dash": "カジキが外洋へ走る！ ラインを出して耐えろ！", "dive": "カジキが深い潮目へ潜る！", "turn": "カジキが巨体を返した！", "rest": "カジキの走りが緩んだ。少しでも巻こう！"},
	},
	"boss_kurodai":
	{
		"id": "boss_kurodai",
		"name": "港のぬし・大岩クロダイ",
		"rarity": "ぬし",
		"min_level": 5,
		"boss": true,
		"weight": 1.0,
		"size_min": 72.0,
		"size_max": 94.0,
		"size_bias": 0.85,
		"sell_price": 2500,
		"food_exp": 180,
		"stamina": 190.0,
		"power": 1.55,
		"speed": 1.08,
		"start_distance": 38.0,
		"start_depth": 18.0,
		"color": "#394956",
		"habitat": "港口の大岩周辺",
		"behavior": "潜水・反転・連続突進を使う港のぬし。",
		"fish_no": "No.030",
		"preferred_bait": "岩ガニ",
		"visual_scale": 1.18,
		"line_anchor_x": 0.430,
		"line_anchor_y": 0.03,
		"motion": {"wave_amp": 0.016, "wave_freq": 2.2, "dash_shift": 0.060, "turn_shift": 0.045, "dive_shift": 0.070, "jitter": 0.002, "depth_bias": 0.030},
		"action_profile": {"dash": 0.34, "dive": 0.26, "turn": 0.20, "rest": 0.20},
		"action_messages": {"dash": "ぬしが激しく突進した！ 巻くのを止めよう！", "dive": "ぬしが海底へ潜る！ 糸を出して耐えよう！", "turn": "ぬしが急反転！ テンションの変化に注意！", "rest": "ぬしの動きが鈍った。今が巻き時だ！"},
	},
}

const NUSHI_FISH: Dictionary = {
	"nushi_harbor_pier":
	{
		"id": "nushi_harbor_pier",
		"name": "堤防の底主",
		"base_fish_id": "maanago",
		"rarity": "レア",
		"min_level": 1,
		"boss": true,
		"nushi": true,
		"weight": 1.0,
		"size_min": 140.0,
		"size_max": 182.0,
		"sell_price": 1680,
		"food_exp": 128,
		"stamina": 197.8,
		"power": 1.40,
		"speed": 0.55,
		"start_distance": 25.0,
		"start_depth": 11.0,
		"color": "#6f5a3d",
		"habitat": "港内・堤防の底",
		"behavior": "雨の日の底で粘り続ける港内の古株。",
		"preferred_bait": "イソメ",
		"visual_scale": 1.38,
		"line_anchor_x": 0.430,
		"line_anchor_y": 0.03,
		"motion": {"wave_amp": 0.012, "wave_freq": 1.8, "dash_shift": 0.032, "turn_shift": 0.030, "dive_shift": 0.062, "jitter": 0.002, "depth_bias": 0.055},
		"action_profile": {"dash": 0.24, "dive": 0.40, "turn": 0.14, "rest": 0.22},
		"action_messages": {"dash": "堤防の底主が底を横へ走る！", "dive": "堤防の底主が底へ張りつく！ 糸を出して粘ろう！", "turn": "堤防の底主が底で向きを変えた。テンション注意！", "rest": "堤防の底主が少し浮いた。巻き上げるチャンス！"},
	},
	"nushi_shallow_sand":
	{
		"id": "nushi_shallow_sand",
		"name": "砂底の座布団",
		"base_fish_id": "hirame",
		"rarity": "レア",
		"min_level": 2,
		"boss": true,
		"nushi": true,
		"weight": 1.0,
		"size_min": 170.0,
		"size_max": 221.0,
		"sell_price": 3280,
		"food_exp": 180,
		"stamina": 253.0,
		"power": 1.59,
		"speed": 0.74,
		"start_distance": 31.0,
		"start_depth": 14.0,
		"color": "#7b6b42",
		"habitat": "砂浜・かけあがりの底",
		"behavior": "霧の日の砂地に張りつき、低く横へ走る。",
		"preferred_bait": "小魚",
		"visual_scale": 1.40,
		"line_anchor_x": 0.430,
		"line_anchor_y": 0.05,
		"motion": {"wave_amp": 0.008, "wave_freq": 1.5, "dash_shift": 0.055, "turn_shift": 0.022, "dive_shift": 0.060, "jitter": 0.001, "depth_bias": 0.070},
		"action_profile": {"dash": 0.30, "dive": 0.42, "turn": 0.12, "rest": 0.16},
		"action_messages": {"dash": "砂底の座布団が底から横へ走った！", "dive": "砂底の座布団が砂地へ張りつく！ 焦らず耐えよう！", "turn": "砂底の座布団が低く向きを変えた。", "rest": "砂底の座布団が浮いた。巻き上げるチャンス！"},
	},
	"nushi_rock_breakwater":
	{
		"id": "nushi_rock_breakwater",
		"name": "磯の黒帝",
		"base_fish_id": "ishidai",
		"rarity": "レア",
		"min_level": 2,
		"boss": true,
		"nushi": true,
		"weight": 1.0,
		"size_min": 130.0,
		"size_max": 169.0,
		"sell_price": 3120,
		"food_exp": 176,
		"stamina": 271.4,
		"power": 1.76,
		"speed": 0.78,
		"start_distance": 32.0,
		"start_depth": 16.0,
		"color": "#5c6268",
		"habitat": "岩礁・消波ブロックの根",
		"behavior": "曇りの日の根周りで、太い縞を揺らして潜る。",
		"preferred_bait": "貝",
		"visual_scale": 1.32,
		"line_anchor_x": 0.420,
		"line_anchor_y": 0.03,
		"motion": {"wave_amp": 0.012, "wave_freq": 2.0, "dash_shift": 0.050, "turn_shift": 0.030, "dive_shift": 0.060, "jitter": 0.001, "depth_bias": 0.045},
		"action_profile": {"dash": 0.34, "dive": 0.34, "turn": 0.12, "rest": 0.20},
		"action_messages": {"dash": "磯の黒帝が岩場へ突っ込む！", "dive": "磯の黒帝が深く潜る！ 糸を出して耐えよう！", "turn": "磯の黒帝が重く反転した。", "rest": "磯の黒帝の抵抗が弱まった。巻き時だ！"},
	},
	"nushi_outer_tide":
	{
		"id": "nushi_outer_tide",
		"name": "潮目の銀狼",
		"base_fish_id": "suzuki",
		"rarity": "レア",
		"min_level": 3,
		"boss": true,
		"nushi": true,
		"weight": 1.0,
		"size_min": 170.0,
		"size_max": 221.0,
		"sell_price": 2080,
		"food_exp": 124,
		"stamina": 211.6,
		"power": 1.51,
		"speed": 1.06,
		"start_distance": 33.0,
		"start_depth": 8.0,
		"color": "#9fa69a",
		"habitat": "港外・潮目の表層",
		"behavior": "雨の潮目を銀色に走り、急反転でラインを揺らす。",
		"preferred_bait": "小魚",
		"visual_scale": 1.49,
		"line_anchor_x": 0.445,
		"line_anchor_y": 0.00,
		"motion": {"wave_amp": 0.020, "wave_freq": 2.8, "dash_shift": 0.065, "turn_shift": 0.070, "dive_shift": 0.018, "jitter": 0.002, "depth_bias": -0.030},
		"action_profile": {"dash": 0.38, "dive": 0.12, "turn": 0.36, "rest": 0.14},
		"action_messages": {"dash": "潮目の銀狼が水面近くを長く走る！", "dive": "潮目の銀狼が潮目の下へ潜る！", "turn": "潮目の銀狼が大きく反転した！ テンションの変化に注意！", "rest": "潮目の銀狼の動きが止まった。距離を詰めよう！"},
	},
	"nushi_south_reef":
	{
		"id": "nushi_south_reef",
		"name": "岩窟の老王",
		"base_fish_id": "kue",
		"rarity": "レア",
		"min_level": 5,
		"boss": true,
		"nushi": true,
		"weight": 1.0,
		"size_min": 260.0,
		"size_max": 338.0,
		"sell_price": 6600,
		"food_exp": 330,
		"stamina": 404.8,
		"power": 2.00,
		"speed": 0.59,
		"start_distance": 36.0,
		"start_depth": 20.0,
		"color": "#6b5b43",
		"habitat": "南の岩礁の大岩穴",
		"behavior": "霧の岩窟で、圧倒的な重さのまま底へ潜り続ける。",
		"preferred_bait": "小魚",
		"visual_scale": 1.59,
		"line_anchor_x": 0.405,
		"line_anchor_y": 0.04,
		"motion": {"wave_amp": 0.007, "wave_freq": 1.4, "dash_shift": 0.034, "turn_shift": 0.020, "dive_shift": 0.085, "jitter": 0.001, "depth_bias": 0.090},
		"action_profile": {"dash": 0.18, "dive": 0.58, "turn": 0.06, "rest": 0.18},
		"action_messages": {"dash": "岩窟の老王が大岩へ突っ込む！", "dive": "岩窟の老王が底へ沈む！ 糸を出して耐えよう！", "turn": "岩窟の老王が重く体を返した。", "rest": "岩窟の老王の重みが少し抜けた。巻き上げよう！"},
	},
	"nushi_bluewater_route":
	{
		"id": "nushi_bluewater_route",
		"name": "回遊の大将",
		"base_fish_id": "buri",
		"rarity": "レア",
		"min_level": 6,
		"boss": true,
		"nushi": true,
		"weight": 1.0,
		"size_min": 220.0,
		"size_max": 286.0,
		"sell_price": 4720,
		"food_exp": 260,
		"stamina": 363.4,
		"power": 1.86,
		"speed": 1.14,
		"start_distance": 42.0,
		"start_depth": 15.0,
		"color": "#6f9097",
		"habitat": "外海・回遊ルート",
		"behavior": "風の強い快晴に回遊し、長い横走りで主導権を奪う。",
		"preferred_bait": "小魚",
		"visual_scale": 1.59,
		"line_anchor_x": 0.440,
		"line_anchor_y": 0.01,
		"motion": {"wave_amp": 0.020, "wave_freq": 3.4, "dash_shift": 0.078, "turn_shift": 0.040, "dive_shift": 0.038, "jitter": 0.002, "depth_bias": 0.010},
		"action_profile": {"dash": 0.50, "dive": 0.22, "turn": 0.12, "rest": 0.16},
		"action_messages": {"dash": "回遊の大将が外海へ走る！ 無理に止めず耐えよう！", "dive": "回遊の大将が深く沈む！", "turn": "回遊の大将が重く向きを変えた。", "rest": "回遊の大将の走りが止まった。巻き上げよう！"},
	},
	"nushi_deep_ocean":
	{
		"id": "nushi_deep_ocean",
		"name": "深淵の重鎮",
		"base_fish_id": "ara",
		"rarity": "レア",
		"min_level": 9,
		"boss": true,
		"nushi": true,
		"weight": 1.0,
		"size_min": 260.0,
		"size_max": 338.0,
		"sell_price": 14400,
		"food_exp": 520,
		"stamina": 547.4,
		"power": 2.00,
		"speed": 0.66,
		"start_distance": 45.0,
		"start_depth": 24.0,
		"color": "#7a5f48",
		"habitat": "外洋の深場の岩礁",
		"behavior": "霧の深場で巨体を沈め、底から離れようとしない。",
		"preferred_bait": "小魚",
		"visual_scale": 1.67,
		"line_anchor_x": 0.405,
		"line_anchor_y": 0.05,
		"motion": {"wave_amp": 0.016, "wave_freq": 2.2, "dash_shift": 0.068, "turn_shift": 0.040, "dive_shift": 0.070, "jitter": 0.001, "depth_bias": 0.036},
		"action_profile": {"dash": 0.40, "dive": 0.30, "turn": 0.12, "rest": 0.18},
		"action_messages": {"dash": "深淵の重鎮が根へ突っ込む！ 無理に巻かず耐えよう！", "dive": "深淵の重鎮が深く潜る！ ラインを出して耐えよう！", "turn": "深淵の重鎮が岩陰で反転した！", "rest": "深淵の重鎮の重い抵抗が緩んだ。今が巻き時だ！"},
	},
}

const COMMON_LOW_LEVEL_FISH_IDS: Array[String] = [
	"aji",
	"mejina",
	"kasago",
	"iwashi",
	"shirogisu",
	"isaki",
	"kawahagi",
	"mebaru",
	"ainame",
	"bora",
]

const NORMAL_FISHING_SPOT_IDS: Array[String] = [
	"harbor_pier",
	"shallow_sand",
	"rock_breakwater",
	"outer_tide",
	"south_reef",
	"bluewater_route",
	"deep_ocean",
]

const FISHING_SPOT_ORDER: Array[String] = [
	"harbor_pier",
	"shallow_sand",
	"rock_breakwater",
	"outer_tide",
	"south_reef",
	"bluewater_route",
	"deep_ocean",
	"harbor_boulder",
]

const FISHING_SPOTS: Dictionary = {
	"harbor_pier":
	{
		"id": "harbor_pier",
		"name": "港内・堤防",
		"short_name": "港内",
		"unlock_level": 1,
		"required_boat_rank": 0,
		"depth_range": [5.0, 10.0],
		"description": "足場が良く、小魚と港内の魚が集まる入門ポイント。",
		"common_modifier": 0.78,
		"featured_fish": ["aji", "mahaze", "umitanago", "sayori", "maanago", "kyusen"],
		"recommended_baits": ["アミエビ", "イソメ", "オキアミ"],
		"boss_spot": false,
		"allowed_fish": ["aji", "mejina", "kasago", "iwashi", "shirogisu", "isaki", "kawahagi", "mebaru", "ainame", "bora", "mahaze", "umitanago", "sappa", "konoshiro", "sayori", "maanago", "kyusen", "nenbutsudai"],
		"fish_weight_modifiers": {"aji": 1.6, "iwashi": 1.5, "mahaze": 2.2, "umitanago": 1.8, "sappa": 1.9, "konoshiro": 1.4, "sayori": 1.5, "maanago": 0.9, "kyusen": 1.3, "nenbutsudai": 1.4},
		"nushi": {"fish_id": "nushi_harbor_pier", "environment_id": "rain", "rig_id": "chokusen", "time_slot_id": "", "hint": "雨の日、堤防の底で竿を折られた奴がいるらしい…"},
	},
	"shallow_sand":
	{
		"id": "shallow_sand",
		"name": "砂浜・かけあがり",
		"short_name": "砂浜",
		"unlock_level": 2,
		"required_boat_rank": 0,
		"depth_range": [7.0, 15.0],
		"description": "砂地を探る。白身魚や底物を狙いやすい。",
		"common_modifier": 0.72,
		"featured_fish": ["shirogisu", "kochi", "hirame", "makogarei", "houbou", "megochi"],
		"recommended_baits": ["イソメ", "小魚", "貝"],
		"boss_spot": false,
		"allowed_fish": ["aji", "mejina", "kasago", "iwashi", "shirogisu", "isaki", "kawahagi", "mebaru", "ainame", "bora", "kochi", "hirame", "makogarei", "ishigarei", "shitabirame", "houbou", "kanagashira", "megochi"],
		"fish_weight_modifiers": {"shirogisu": 1.8, "kawahagi": 1.5, "kochi": 2.0, "hirame": 1.6, "makogarei": 1.8, "ishigarei": 1.5, "shitabirame": 1.7, "houbou": 1.3, "kanagashira": 1.5, "megochi": 1.8},
		"nushi": {"fish_id": "nushi_shallow_sand", "environment_id": "fog", "rig_id": "nomase", "time_slot_id": "", "hint": "霧の砂浜で、座布団みたいな影が小魚をさらうらしい…"},
	},
	"rock_breakwater":
	{
		"id": "rock_breakwater",
		"name": "岩礁・消波ブロック",
		"short_name": "岩礁",
		"unlock_level": 2,
		"required_boat_rank": 0,
		"depth_range": [9.0, 17.0],
		"description": "根周りを攻める。潜る魚が多く、糸を出す判断が重要。",
		"common_modifier": 0.58,
		"featured_fish": ["kasago", "ishidai", "ishigakidai", "kurosoi", "kobudai", "onikasago"],
		"recommended_baits": ["イソメ", "貝", "岩ガニ"],
		"boss_spot": false,
		"allowed_fish": ["aji", "mejina", "kasago", "iwashi", "shirogisu", "isaki", "kawahagi", "mebaru", "ainame", "bora", "ishidai", "ishigakidai", "kurosoi", "murasoi", "takenokomebaru", "oomonhata", "onikasago", "kobudai"],
		"fish_weight_modifiers": {"mejina": 1.2, "kasago": 1.6, "mebaru": 1.7, "ainame": 1.5, "ishidai": 1.8, "ishigakidai": 1.7, "kurosoi": 1.8, "murasoi": 1.7, "takenokomebaru": 1.4, "oomonhata": 1.4, "onikasago": 1.1, "kobudai": 0.9},
		"nushi": {"fish_id": "nushi_rock_breakwater", "environment_id": "cloudy", "rig_id": "kani", "time_slot_id": "", "hint": "曇りの日、カニ餌を岩の影へ落とすと黒い縞が出るらしい…"},
	},
	"outer_tide":
	{
		"id": "outer_tide",
		"name": "港外・潮目",
		"short_name": "潮目",
		"unlock_level": 3,
		"required_boat_rank": 0,
		"depth_range": [8.0, 16.0],
		"description": "潮通しのよい外側。横走りする魚の反応が多い。",
		"common_modifier": 0.62,
		"featured_fish": ["saba", "suzuki", "kamasu", "sawara", "datsu", "suma"],
		"recommended_baits": ["小魚", "大型ルアー", "オキアミ"],
		"boss_spot": false,
		"allowed_fish": ["aji", "mejina", "kasago", "iwashi", "shirogisu", "isaki", "kawahagi", "mebaru", "ainame", "bora", "saba", "suzuki", "kamasu", "tachiuo", "sawara", "datsu", "hirasouda", "suma"],
		"fish_weight_modifiers": {"saba": 1.9, "suzuki": 1.7, "kamasu": 2.1, "tachiuo": 1.7, "sawara": 1.4, "datsu": 1.6, "hirasouda": 1.4, "suma": 1.1},
		"nushi": {"fish_id": "nushi_outer_tide", "environment_id": "rain", "rig_id": "nomase", "time_slot_id": "", "hint": "雨の潮目で泳がせると、銀色の大物が水面を割るらしい…"},
	},
	"south_reef":
	{
		"id": "south_reef",
		"name": "南の岩礁",
		"short_name": "南岩礁",
		"unlock_level": 5,
		"required_boat_rank": 1,
		"depth_range": [12.0, 21.0],
		"description": "南側の根とサンゴ帯。色鮮やかな岩礁魚と大物の気配がある。",
		"common_modifier": 0.35,
		"featured_fish": ["madai", "akahata", "fuefukidai", "aobudai", "kue", "meichidai"],
		"recommended_baits": ["オキアミ", "小魚", "貝", "岩ガニ"],
		"boss_spot": false,
		"allowed_fish": ["aji", "mejina", "kasago", "iwashi", "shirogisu", "isaki", "kawahagi", "mebaru", "ainame", "bora", "madai", "akahata", "fuefukidai", "aobudai", "kue", "ojisan", "takabe", "ira", "meichidai"],
		"fish_weight_modifiers": {"madai": 1.3, "akahata": 1.8, "fuefukidai": 1.8, "aobudai": 1.8, "kue": 1.2, "ojisan": 1.6, "takabe": 1.7, "ira": 1.4, "meichidai": 1.1},
		"nushi": {"fish_id": "nushi_south_reef", "environment_id": "fog", "rig_id": "kani", "time_slot_id": "", "hint": "霧の南岩礁でカニ餌を沈めると、岩窟の主が動くらしい…"},
	},
	"bluewater_route":
	{
		"id": "bluewater_route",
		"name": "外海・回遊ルート",
		"short_name": "外海",
		"unlock_level": 6,
		"required_boat_rank": 2,
		"depth_range": [10.0, 20.0],
		"description": "外海へ続く潮筋。青物や表層を走る魚を狙う。",
		"common_modifier": 0.22,
		"featured_fish": ["kanpachi", "buri", "katsuo", "shiira", "hiramasa", "shimaaji"],
		"recommended_baits": ["小魚", "大型ルアー", "オキアミ"],
		"boss_spot": false,
		"allowed_fish": ["aji", "mejina", "kasago", "iwashi", "shirogisu", "isaki", "kawahagi", "mebaru", "ainame", "bora", "kanpachi", "buri", "katsuo", "shiira", "hiramasa", "shimaaji", "tsumuburi", "gingameaji", "kaiwari"],
		"fish_weight_modifiers": {"kanpachi": 2.2, "buri": 2.1, "katsuo": 2.0, "shiira": 2.0, "hiramasa": 1.6, "shimaaji": 1.2, "tsumuburi": 1.0, "gingameaji": 1.0, "kaiwari": 1.4},
		"nushi": {"fish_id": "nushi_bluewater_route", "environment_id": "sunny_windy", "rig_id": "jigging", "time_slot_id": "", "hint": "風の強い快晴、ジグを速く通すと群れの大将が追うらしい…"},
	},
	"deep_ocean":
	{
		"id": "deep_ocean",
		"name": "外洋の深場",
		"short_name": "外洋",
		"unlock_level": 9,
		"required_boat_rank": 3,
		"depth_range": [15.0, 25.0],
		"description": "外洋の深い潮目。終盤の大物を低確率で狙う。",
		"common_modifier": 0.10,
		"featured_fish": ["rouninaji", "kajiki", "kihada", "akamutsu", "kinmedai", "ara"],
		"recommended_baits": ["小魚", "大型ルアー", "貝"],
		"boss_spot": false,
		"allowed_fish": ["aji", "mejina", "kasago", "iwashi", "shirogisu", "isaki", "kawahagi", "mebaru", "ainame", "bora", "rouninaji", "kajiki", "kihada", "binnaga", "mebachi", "akamutsu", "kinmedai", "ara", "medai"],
		"fish_weight_modifiers": {"rouninaji": 0.6, "kajiki": 0.8, "kihada": 0.8, "binnaga": 0.7, "mebachi": 0.8, "akamutsu": 0.7, "kinmedai": 0.7, "ara": 0.7, "medai": 0.7},
		"nushi": {"fish_id": "nushi_deep_ocean", "environment_id": "fog", "rig_id": "nomase", "time_slot_id": "", "hint": "霧の深場で泳がせると、底から重い影が浮くことがあるらしい…"},
	},
	"harbor_boulder":
	{
		"id": "harbor_boulder",
		"name": "港の大岩",
		"short_name": "大岩",
		"unlock_level": 5,
		"required_boat_rank": 0,
		"depth_range": [16.0, 22.0],
		"description": "港口の大岩周辺。港のぬしに挑む専用ポイント。",
		"common_modifier": 0.0,
		"featured_fish": ["boss_kurodai"],
		"recommended_baits": ["岩ガニ"],
		"boss_spot": true,
		"allowed_fish": ["boss_kurodai"],
		"fish_weight_modifiers": {},
	},
}
const FISHING_ENVIRONMENT_ORDER: Array[String] = [
	"sunny_calm",
	"sunny_windy",
	"partly_cloudy",
	"cloudy",
	"rain",
	"fog",
]

const FISHING_ENVIRONMENTS: Dictionary = {
	"sunny_calm":
	{
		"id": "sunny_calm",
		"weather_id": "sunny",
		"weather_label": "快晴",
		"wind_id": "weak",
		"wind_label": "風 弱",
		"surface_bgm_key": "calm",
		"weight": 0.30,
			"fish_weight_modifiers": {
				"aji": 1.15,
				"iwashi": 1.15,
				"shirogisu": 1.10,
				"isaki": 1.08,
				"sappa": 1.10,
				"mahaze": 1.08,
				"sayori": 1.12,
				"takabe": 1.10,
			},
	},
	"sunny_windy":
	{
		"id": "sunny_windy",
		"weather_id": "sunny",
		"weather_label": "快晴",
		"wind_id": "strong",
		"wind_label": "風 強",
		"surface_bgm_key": "windy",
		"weight": 0.10,
			"fish_weight_modifiers": {
				"saba": 1.25,
				"kamasu": 1.25,
				"tachiuo": 1.18,
				"shiira": 1.15,
				"sawara": 1.28,
				"datsu": 1.18,
				"hirasouda": 1.22,
				"suma": 1.18,
				"tsumuburi": 1.12,
			},
	},
	"partly_cloudy":
	{
		"id": "partly_cloudy",
		"weather_id": "partly_cloudy",
		"weather_label": "晴れ曇り",
		"wind_id": "weak",
		"wind_label": "風 弱",
		"surface_bgm_key": "calm",
		"weight": 0.22,
			"fish_weight_modifiers": {
				"mejina": 1.12,
				"isaki": 1.15,
				"kawahagi": 1.12,
				"madai": 1.10,
				"bora": 1.08,
				"umitanago": 1.12,
				"konoshiro": 1.10,
				"meichidai": 1.12,
				"shimaaji": 1.10,
				"kaiwari": 1.12,
			},
	},
	"cloudy":
	{
		"id": "cloudy",
		"weather_id": "cloudy",
		"weather_label": "曇り",
		"wind_id": "weak",
		"wind_label": "風 弱",
		"surface_bgm_key": "calm",
		"weight": 0.18,
			"fish_weight_modifiers": {
				"kasago": 1.20,
				"mebaru": 1.35,
				"ainame": 1.25,
				"suzuki": 1.35,
				"ishidai": 1.15,
				"maanago": 1.25,
				"kurosoi": 1.35,
				"murasoi": 1.25,
				"takenokomebaru": 1.20,
				"oomonhata": 1.12,
			},
	},
	"rain":
	{
		"id": "rain",
		"weather_id": "rain",
		"weather_label": "小雨",
		"wind_id": "strong",
		"wind_label": "風 強",
		"surface_bgm_key": "windy",
		"weight": 0.12,
			"fish_weight_modifiers": {
				"suzuki": 1.80,
				"mebaru": 1.45,
				"kasago": 1.25,
				"bora": 1.25,
				"tachiuo": 1.20,
				"kue": 1.12,
				"maanago": 1.35,
				"kurosoi": 1.25,
				"sawara": 1.20,
				"akamutsu": 1.18,
				"ara": 1.12,
			},
	},
	"fog":
	{
		"id": "fog",
		"weather_id": "fog",
		"weather_label": "霧",
		"wind_id": "weak",
		"wind_label": "風 弱",
		"surface_bgm_key": "calm",
		"weight": 0.08,
			"fish_weight_modifiers": {
				"hirame": 1.25,
				"kochi": 1.20,
				"akahata": 1.25,
				"kue": 1.35,
				"rouninaji": 1.25,
				"kajiki": 1.20,
				"hiramasa": 1.18,
				"makogarei": 1.22,
				"ishigarei": 1.18,
				"shitabirame": 1.16,
				"onikasago": 1.15,
				"kinmedai": 1.25,
				"medai": 1.18,
			},
	},
}

const RECIPES: Dictionary = {
	"salt_grill":
		{
			"id": "salt_grill",
			"name": "塩焼き",
			"unlock_level": 1,
			"exp_multiplier": 1.0,
			"allow_all_fish": true,
			"allowed_fish": ["aji", "mejina", "kasago", "isaki", "saba", "suzuki", "madai", "hirame", "kawahagi", "iwashi", "shirogisu", "mebaru", "ainame", "bora", "kamasu", "kochi", "tachiuo", "ishidai", "akahata", "fuefukidai", "aobudai", "kanpachi", "buri", "katsuo", "shiira", "kue", "hiramasa", "rouninaji", "kajiki", "boss_kurodai"],
		"description": "素材の味を活かす基本料理。",
		"buff_stat": "max_energy",
		"buff_value": 0.05,
		"buff_text": "次の釣行で最大体力 +5%",
	},
	"sashimi":
	{
		"id": "sashimi",
		"name": "刺身",
		"unlock_level": 2,
		"exp_multiplier": 1.2,
		"allowed_fish": ["aji", "mejina", "isaki", "saba", "suzuki", "madai", "hirame", "kawahagi", "iwashi", "shirogisu", "mebaru", "kamasu", "tachiuo", "ishidai", "akahata", "fuefukidai", "aobudai", "kanpachi", "buri", "katsuo", "shiira", "hiramasa", "rouninaji", "kajiki", "boss_kurodai"],
		"description": "鮮度を活かした一皿。アワセの猶予が伸びる。",
		"buff_stat": "bite_window",
		"buff_value": 0.35,
		"buff_text": "次の釣行でアワセ猶予 +0.35秒",
	},
	"simmered":
	{
		"id": "simmered",
		"name": "煮付け",
		"unlock_level": 3,
		"exp_multiplier": 1.35,
		"allowed_fish": ["mejina", "kasago", "isaki", "madai", "hirame", "kawahagi", "mebaru", "ainame", "bora", "kochi", "tachiuo", "ishidai", "akahata", "fuefukidai", "aobudai", "kue", "boss_kurodai"],
		"description": "じっくり煮込んだ料理。安全なテンション域が広がる。",
		"buff_stat": "safe_range",
		"buff_value": 0.05,
		"buff_text": "次の釣行で安全テンション域 +5%",
	},
	"soup":
		{
			"id": "soup",
			"name": "つみれ汁",
			"unlock_level": 4,
			"exp_multiplier": 1.5,
			"allow_all_fish": true,
			"allowed_fish": ["aji", "mejina", "kasago", "isaki", "saba", "suzuki", "madai", "hirame", "kawahagi", "iwashi", "shirogisu", "mebaru", "ainame", "bora", "kamasu", "kochi", "tachiuo", "ishidai", "akahata", "fuefukidai", "aobudai", "kanpachi", "buri", "katsuo", "shiira", "kue", "hiramasa", "rouninaji", "kajiki", "boss_kurodai"],
		"description": "身体が温まる汁物。体力回復が速くなる。",
		"buff_stat": "energy_regen",
		"buff_value": 0.18,
		"buff_text": "次の釣行で体力回復 +18%",
	},
	"fry":
	{
		"id": "fry",
		"name": "魚フライ",
		"unlock_level": 5,
		"exp_multiplier": 1.6,
		"allowed_fish": ["aji", "isaki", "saba", "suzuki", "madai", "hirame", "kawahagi", "iwashi", "shirogisu", "mebaru", "ainame", "kamasu", "kochi", "tachiuo", "akahata", "fuefukidai", "kanpachi", "buri", "katsuo", "shiira", "hiramasa"],
		"description": "食べ応えのある揚げ物。巻き上げ力が増す。",
		"buff_stat": "reel_power",
		"buff_value": 0.10,
		"buff_text": "次の釣行で巻力 +10%",
	},
}

const QUEST_TEMPLATES: Dictionary = {
	"bulk_common":
	{
		"id": "bulk_common",
		"kind": "delivery",
		"rarity": "コモン",
		"min_count": 3,
		"max_count": 5,
		"reward_multiplier": 1.6,
	},
	"bulk_uncommon":
	{
		"id": "bulk_uncommon",
		"kind": "delivery",
		"rarity": "アンコモン",
		"min_count": 2,
		"max_count": 3,
		"reward_multiplier": 1.8,
	},
	"cuisine":
	{
		"id": "cuisine",
		"kind": "delivery",
		"min_count": 1,
		"max_count": 1,
		"reward_multiplier": 2.0,
	},
	"size_record":
	{
		"id": "size_record",
		"kind": "record",
		"target_ratio": 0.62,
		"target_snap_cm": 5.0,
		"reward_multiplier": 2.5,
	},
	"rare_order":
	{
		"id": "rare_order",
		"kind": "delivery",
		"rarity": "レア",
		"min_count": 1,
		"max_count": 1,
		"reward_multiplier": 2.2,
		"min_level": 8,
	},
	"zarigani_kid":
	{
		"id": "zarigani_kid",
		"kind": "delivery",
		"fish_id": "zarigani",
		"min_count": 3,
		"max_count": 3,
		"reward_multiplier": 0.0,
		"min_phase": "E8",
	},
}

const ROD_ORDER: Array[String] = [
	"starter",
	"iso",
	"offshore",
	"big_game",
	"marlin",
]

const RODS: Dictionary = {
	"starter":
	{
		"id": "starter",
		"name": "港の入門竿",
		"price": 0,
		"reel_multiplier": 1.0,
		"line_limit_bonus": 0.0,
		"technique_bonus": 0,
		"description": "扱いやすい標準装備。",
	},
	"iso":
	{
		"id": "iso",
		"name": "磯竿・潮風",
		"price": 850,
		"reel_multiplier": 1.12,
		"line_limit_bonus": 0.05,
		"technique_bonus": 1,
		"description": "粘りがあり、強い引きにも耐える。",
	},
	"offshore":
	{
		"id": "offshore",
		"name": "外海竿・青嵐",
		"price": 2600,
		"reel_multiplier": 1.30,
		"line_limit_bonus": 0.10,
		"technique_bonus": 2,
		"description": "外海の青物や回遊魚に備える上位竿。",
	},
	"big_game":
	{
		"id": "big_game",
		"name": "大物竿・剛潮",
		"price": 5200,
		"reel_multiplier": 1.48,
		"line_limit_bonus": 0.18,
		"technique_bonus": 3,
		"description": "クエやヒラマサ級の重い引きに耐える剛竿。",
	},
	"marlin":
	{
		"id": "marlin",
		"name": "カジキ竿・蒼槍",
		"price": 9000,
		"reel_multiplier": 1.68,
		"line_limit_bonus": 0.30,
		"technique_bonus": 4,
		"description": "外洋の超大型魚を追う終盤用タックル。",
	},
}

const RIG_ORDER: Array[String] = [
	"sabiki",
	"uki",
	"chokusen",
	"nomase",
	"jigging",
	"kani",
	"shokunin",
]

const RIGS: Dictionary = {
	"sabiki":
	{
		"id": "sabiki",
		"name": "サビキ仕掛け",
		"price": 0,
		"bait_types": ["アミエビ"],
		"unlock_level": 1,
		"description": "小魚の群れを狙う入門仕掛け。",
	},
	"uki":
	{
		"id": "uki",
		"name": "ウキ釣り仕掛け",
		"price": 400,
		"bait_types": ["オキアミ", "練りエサ"],
		"unlock_level": 2,
		"description": "潮に流して中層から表層の魚を誘う仕掛け。",
	},
	"chokusen":
	{
		"id": "chokusen",
		"name": "胴突き仕掛け",
		"price": 600,
		"bait_types": ["イソメ", "貝", "アサリ"],
		"unlock_level": 2,
		"description": "底物や岩場の魚を丁寧に探る仕掛け。",
	},
	"nomase":
	{
		"id": "nomase",
		"name": "泳がせ仕掛け",
		"price": 1500,
		"bait_types": ["小魚"],
		"unlock_level": 4,
		"description": "活き餌で大型魚の反応を狙う仕掛け。",
	},
	"jigging":
	{
		"id": "jigging",
		"name": "ルアー・ジグ",
		"price": 2200,
		"bait_types": ["大型ルアー"],
		"unlock_level": 6,
		"description": "外海の青物や回遊魚を速い誘いで狙う仕掛け。",
	},
	"kani":
	{
		"id": "kani",
		"name": "カニ餌仕掛け",
		"price": 1000,
		"bait_types": ["岩ガニ"],
		"unlock_level": 5,
		"description": "石物やぬし級の魚に備える専用寄りの仕掛け。",
	},
	"shokunin":
	{
		"id": "shokunin",
		"name": "職人仕掛け",
		"price": 0,
		"bait_types": ["イソメ", "オキアミ", "小魚"],
		"unlock_level": 1,
		"shop_hidden": true,
		"description": "港の常連たちから贈られた万能仕掛け。",
	},
}

const BOAT_ORDER: Array[String] = [
	"skiff",
	"offshore_boat",
	"bluewater_boat",
]

const BOATS: Dictionary = {
	"skiff":
	{
		"id": "skiff",
		"name": "小型船・浜風",
		"short_name": "小型船",
		"rank": 1,
		"price": 3600,
		"description": "港から少し離れた南の岩礁へ向かえる小回りの利く船。",
		"access_text": "南の岩礁まで出航可能",
	},
	"offshore_boat":
	{
		"id": "offshore_boat",
		"name": "沖釣り船・潮路",
		"short_name": "沖釣り船",
		"rank": 2,
		"price": 8200,
		"description": "外海の回遊ルートまで出られる安定した釣り船。",
		"access_text": "外海・回遊ルートまで出航可能",
	},
	"bluewater_boat":
	{
		"id": "bluewater_boat",
		"name": "外洋船・群青",
		"short_name": "外洋船",
		"rank": 3,
		"price": 14500,
		"description": "深い潮目と外洋の大物を狙うための本格船。",
		"access_text": "外洋の深場まで出航可能",
	},
}
